export const shipObject = {
  "Nova Raiders": {
    fighter: {
      factionName: "Nova Raiders",
      shipId: "FG-ID:" + " " + new Date().getMilliseconds(5),
      type: "Fighter",
      x: 100,
      y: 100,
      width: 68,
      height: 86,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image: "assets/ShipImages/NR/fighterNR.png",
      maxHP: 20,
      hp: 20,
      damageThreshold: 1,
      threatLevel: 15,
      moveDistance: 80,
      weaponType: ["Light Cannon"],
      firingArc: "Forward(90°)",
      weaponDamage: "1d4",
      weaponRange: 30,
      pointValue: 1,
      specialOrders: {
        "All Ahead Full": false,
        "Combine Fire": false,
        "Evasive Maneuvers": false,
      },
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Light Cannon": false,
      },
      shipActions: {
        move: false,
        attack: false,
        specialOrder: false,
      },
      isPendingDestruction: false,
    },

    destroyer: {
      factionName: "Nova Raiders",
      shipId: "DE-ID:" + " " + new Date().getMilliseconds(5),
      type: "Destroyer",
      x: 100,
      y: 100,

      width: 104,
      height: 208,
      isSelected: false,

      isToggled: false,
      rotation_angle: 0,
      image: "assets/ShipImages/NR/destroyerNR.png",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 8,
      hp: 8,
      damageThreshold: 4,
      threatLevel: 10,
      moveDistance: 60,
      weaponType: ["Medium Cannon"],
      firingArc: "Forward(90°)",
      weaponDamage: "1d10",
      weaponRange: 30,
      pointValue: 30,
      specialOrders: {
        "All Ahead Full": false,
        "Anti-Fighter Barrage": false,
        "Power Up Main Guns": false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Medium Cannon": false,
      },
      shipActions: {
        move: false,
        attack: false,
        specialOrder: false,
      },
      isPendingDestruction: false,
    },
    cruiser: {
      factionName: "Nova Raiders",
      shipId: "CR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Cruiser",
      x: 100,
      y: 100,
      width: 123,
      height: 245,
      isSelected: false,
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      isToggled: false,
      rotation_angle: 0,
      image: "assets/ShipImages/NR/cruiserNR.png",
      maxHP: 12,
      hp: 12,
      damageThreshold: 6,
      threatLevel: 8,
      moveDistance: 50,
      weaponType: ["Heavy Cannon", "Plasma Cannon"],
      firingArc: "Forward(90°) \nPortside(90°)/Starboard(90°)",
      weaponDamage: "1d8 \n1d10",
      weaponRange: "30ft \n60ft",
      pointValue: 80,
      specialOrders: {
        "All Ahead Full": false,
        "All Systems Fire": false,
        "Reinforce Shields": false,
        Broadside: false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Heavy Cannon": false,
        "Plasma Cannon": false,
      },
      shipActions: {
        move: false,
        attack: false,
        specialOrder: false,
      },
      isPendingDestruction: false,
    },
    carrier: {
      factionName: "Nova Raiders",
      shipId: "CA-ID:" + " " + new Date().getMilliseconds(5),
      type: "Carrier",
      x: 100,
      y: 100,
      width: 104,
      height: 208,
      isSelected: false,

      isToggled: false,
      rotation_angle: 0,
      image: "assets/ShipImages/NR/carrierNR.png",
      maxHP: 14,
      hp: 14,
      damageThreshold: 7,
      threatLevel: 9,
      moveDistance: 40,
      weaponType: ["Missile Battery"],
      weaponStatus: { "Missile Battery": false },
      firingArc: "Forward(90°) \nAll(360°)",
      weaponDamage: "1d8 \n1d6",
      weaponRange: "30ft-120ft \n15ft-60ft",
      pointValue: 120,
      specialOrders: {
        "All Ahead Full": false,
        "Reinforce Shields": false,
        "Launch Fighters": false,
        "All Systems Fire": false,
      },
      shipActions: {
        move: false,
        attack: false,
        specialOrder: false,
      },
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      hasBeenInteractedWith: false,
      capacity: 20,
      isPendingDestruction: false,
    },
    dreadnought: {
      factionName: "Nova Raiders",
      shipId: "DR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Dreadnought",
      x: 100,
      y: 100,
      width: 218,
      height: 371,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image: "assets/ShipImages/NR/dreadNR.png",
      hp: 30,
      damageThreshold: 4,
      threatLevel: 8,
      moveDistance: 30,
      weaponType: ["Ion Particle Beam", "Plasma Cannon", "350mm Railgun"],
      firingArc:
        "Forward(90°) \nPortside(90°)/Starboard(90°) \nForward(90°)/Aft(90°)",
      weaponDamage: "1d12\n1d10\n1d8",
      weaponRange: "30ft-60ft \n60ft \n30ft-120ft",
      pointValue: 240,
      specialOrders: {
        "All Ahead Full": false,
        "Reinforce Shields": false,
        "All Systems Fire": false,
        "Charge Ion Beam": false,
      },
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Ion Particle Beam": false,
        "Plasma Cannon": false,
        "350mm Railgun": false,
      },
      shipActions: {
        move: false,
        attack: false,
        specialOrder: false,
      },
      isPendingDestruction: false,
    },
  },
  "The Zyrrians": {
    fighter: {
      factionName: "The Zyrrians",
      shipId: "FG-ID:" + " " + new Date().getMilliseconds(5),
      type: "Fighter",
      x: 100,
      y: 100,
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      width: 68,
      height: 86,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image: "assets/ShipImages/ZY/fighterZY.png",
      maxHP: 20,
      hp: 20,
      damageThreshold: 1,
      threatLevel: 15,
      moveDistance: 80,
      weaponType: ["Light Cannon"],
      firingArc: "Forward(90°)",
      weaponDamage: "1d4",
      weaponRange: 30,
      pointValue: 1,
      specialOrders: {
        "All Ahead Full": false,
        "Combine Fire": false,
        "Evasive Maneuvers": false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Light Cannon": false,
      },
      shipActions: {
        move: false,
        attack: false,
        specialOrder: false,
      },
      isPendingDestruction: false,
    },

    destroyer: {
      factionName: "The Zyrrians",
      shipId: "DE-ID:" + " " + new Date().getMilliseconds(5),
      type: "Destroyer",
      x: 100,
      y: 100,
      width: 104,
      height: 208,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image: "assets/ShipImages/ZY/destroyerZY.png",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 8,
      hp: 8,
      damageThreshold: 4,
      threatLevel: 10,
      moveDistance: 60,
      weaponType: ["Medium Cannon"],
      firingArc: "Forward(90°)",
      weaponDamage: "1d10",
      weaponRange: 30,
      pointValue: 30,
      specialOrders: {
        "All Ahead Full": false,
        "Anti-Fighter Barrage": false,
        "Power Up Main Guns": false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Medium Cannon": false,
      },
      shipActions: {
        move: false,
        attack: false,
        specialOrder: false,
      },
      isPendingDestruction: false,
    },
    cruiser: {
      factionName: "The Zyrrians",
      shipId: "CR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Cruiser",
      x: 100,
      y: 100,
      width: 123,
      height: 245,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image: "assets/ShipImages/ZY/cruiserZY.png",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 12,
      hp: 12,
      damageThreshold: 6,
      threatLevel: 8,
      moveDistance: 50,
      weaponType: ["Heavy Cannon", "Plasma Cannon"],
      firingArc: "Forward(90°) \nPortside(90°)/Starboard(90°)",
      weaponDamage: "1d8 \n1d10",
      weaponRange: "30ft \n60ft",
      pointValue: 80,
      specialOrders: {
        "All Ahead Full": false,
        "All Systems Fire": false,
        "Reinforce Shields": false,
        Broadside: false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Heavy Cannon": false,
        "Plasma Cannon": false,
      },
      shipActions: {
        move: false,
        attack: false,
        specialOrder: false,
      },
      isPendingDestruction: false,
    },
    carrier: {
      factionName: "The Zyrrians",
      shipId: "CA-ID:" + " " + new Date().getMilliseconds(5),
      type: "Carrier",
      x: 100,
      y: 100,
      width: 104,
      height: 208,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image: "assets/ShipImages/ZY/carrierZY.png",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 14,
      hp: 14,
      damageThreshold: 7,
      threatLevel: 9,
      moveDistance: 40,
      weaponType: ["Missile Battery"],
      weaponStatus: { "Missile Battery": false },
      firingArc: "Forward(90°) \nAll(360°)",
      weaponDamage: "1d8 \n1d6",
      weaponRange: "30ft-120ft \n15ft-60ft",
      pointValue: 120,
      specialOrders: {
        "All Ahead Full": false,
        "Reinforce Shields": false,
        "Launch Fighters": false,
        "All Systems Fire": false,
      },
      hasBeenInteractedWith: false,
      capacity: 20,
      shipActions: {
        move: false,
        attack: false,
        specialOrder: false,
      },
      isPendingDestruction: false,
    },
    dreadnought: {
      factionName: "The Zyrrians",
      shipId: "DR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Dreadnought",
      x: 100,
      y: 100,
      width: 218,
      height: 371,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image: "assets/ShipImages/ZY/dreadZY.png",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 30,
      hp: 30,
      damageThreshold: 4,
      threatLevel: 8,
      moveDistance: 30,
      weaponType: ["Ion Particle Beam", "Plasma Cannon", "350mm Railgun"],
      firingArc:
        "Forward(90°) \nPortside(90°)/Starboard(90°) \nForward(90°)/Aft(90°)",
      weaponDamage: "1d12\n1d10\n1d8",
      weaponRange: "30ft-60ft \n60ft \n30ft-120ft",
      pointValue: 240,
      specialOrders: {
        "All Ahead Full": false,
        "Reinforce Shields": false,
        "All Systems Fire": false,
        "Charge Ion Beam": false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Ion Particle Beam": false,
        "Plasma Cannon": false,
        "350mm Railgun": false,
      },
      shipActions: {
        move: false,
        attack: false,
        specialOrder: false,
      },
      isPendingDestruction: false,
    },
  },
  "Voidborn Marauders": {
    fighter: {
      factionName: "Voidborn Marauders",
      shipId: "FG-ID:" + " " + new Date().getMilliseconds(5),
      type: "Fighter",
      x: 100,
      y: 100,
      width: 68,
      height: 86,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image: "assets/ShipImages/VM/fighter.png",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 20,
      hp: 20,
      damageThreshold: 1,
      threatLevel: 15,
      moveDistance: 80,
      weaponType: ["Light Cannon"],
      firingArc: "Forward(90°)",
      weaponDamage: "1d4",
      weaponRange: 30,
      pointValue: 1,
      specialOrders: {
        "All Ahead Full": false,
        "Combine Fire": false,
        "Evasive Maneuvers": false,
      },
      weaponStatus: {
        "Light Cannon": false,
      },
      shipActions: {
        move: false,
        attack: false,
        specialOrder: false,
      },
      isPendingDestruction: false,
    },

    destroyer: {
      factionName: "Voidborn Marauders",
      shipId: "DE-ID:" + " " + new Date().getMilliseconds(5),
      type: "Destroyer",
      x: 100,
      y: 100,
      width: 104,
      height: 208,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image: "assets/ShipImages/VM/destroyer.png",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 8,
      hp: 8,
      damageThreshold: 4,
      threatLevel: 10,
      moveDistance: 60,
      weaponType: ["Medium Cannon"],
      firingArc: "Forward(90°)",
      weaponDamage: "1d10",
      weaponRange: 30,
      pointValue: 30,
      specialOrders: {
        "All Ahead Full": false,
        "Anti-Fighter Barrage": false,
        "Power Up Main Guns": false,
      },
      weaponStatus: {
        "Medium Cannon": false,
      },
      shipActions: {
        move: false,
        attack: false,
        specialOrder: false,
      },
      isPendingDestruction: false,
    },
    cruiser: {
      factionName: "Voidborn Marauders",
      shipId: "CR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Cruiser",
      x: 100,
      y: 100,
      width: 123,
      height: 245,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image: "assets/ShipImages/VM/cruiser.png",
      maxHP: 12,
      hp: 12,
      damageThreshold: 6,
      threatLevel: 8,
      moveDistance: 50,
      weaponType: ["Heavy Cannon", "Plasma Cannon"],
      firingArc: "Forward(90°) \nPortside(90°)/Starboard(90°)",
      weaponDamage: "1d8 \n1d10",
      weaponRange: "30ft \n60ft",
      pointValue: 80,
      specialOrders: {
        "All Ahead Full": false,
        "All Systems Fire": false,
        "Reinforce Shields": false,
        Broadside: false,
      },
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      weaponStatus: {
        "Heavy Cannon": false,
        "Plasma Cannon": false,
      },
      shipActions: {
        move: false,
        attack: false,
        specialOrder: false,
      },
      isPendingDestruction: false,
    },
    carrier: {
      factionName: "Voidborn Marauders",
      shipId: "CA-ID:" + " " + new Date().getMilliseconds(5),
      type: "Carrier",
      x: 100,
      y: 100,
      width: 104,
      height: 208,
      isSelected: false,

      isToggled: false,
      rotation_angle: 0,
      image: "assets/ShipImages/VM/carrier.png",
      maxHP: 14,
      hp: 14,
      damageThreshold: 7,
      threatLevel: 9,
      moveDistance: 40,
      firingArc: "Forward(90°) \nAll(360°)",
      weaponDamage: "1d8 \n1d6",
      weaponRange: "30ft-120ft \n15ft-60ft",
      pointValue: 120,
      specialOrders: {
        "All Ahead Full": false,
        "Reinforce Shields": false,
        "Launch Fighters": false,
        "All Systems Fire": false,
      },
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      weaponType: ["Missile Battery"],
      weaponStatus: { "Missile Battery": false },
      capacity: 20,
      shipActions: {
        move: false,
        attack: false,
        specialOrder: false,
      },
      isPendingDestruction: false,
    },
    dreadnought: {
      factionName: "Voidborn Marauders",
      shipId: "DR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Dreadnought",
      x: 100,
      y: 100,
      width: 218,
      height: 371,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image: "assets/ShipImages/VM/dread.png",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 30,
      hp: 30,
      damageThreshold: 4,
      threatLevel: 8,
      moveDistance: 30,
      weaponType: ["Ion Particle Beam", "Plasma Cannon", "350mm Railgun"],
      firingArc:
        "Forward(90°) \nPortside(90°)/Starboard(90°) \nForward(90°)/Aft(90°)",
      weaponDamage: "1d12\n1d10\n1d8",
      weaponRange: "30ft-60ft \n60ft \n30ft-120ft",
      pointValue: 240,
      specialOrders: {
        "All Ahead Full": false,
        "Reinforce Shields": false,
        "All Systems Fire": false,
        "Charge Ion Beam": false,
      },
      moveDistanceBonus: 0,
      weaponStatus: {
        "Ion Particle Beam": false,
        "Plasma Cannon": false,
        "350mm Railgun": false,
      },
      shipActions: {
        move: false,
        attack: false,
        specialOrder: false,
      },
      isPendingDestruction: false,
    },
  },
  "Star Reapers": {
    fighter: {
      factionName: "Star Reapers",
      shipId: "FG-ID:" + " " + new Date().getMilliseconds(5),
      type: "Fighter",
      x: 100,
      y: 100,
      width: 68,
      height: 86,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image: "assets/ShipImages/SR/fighter.png",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 20,
      hp: 20,
      damageThreshold: 1,
      threatLevel: 15,
      moveDistance: 80,
      weaponType: ["Light Cannon"],
      firingArc: "Forward(90°)",
      weaponDamage: "1d4",
      weaponRange: 30,
      pointValue: 1,
      specialOrders: {
        "All Ahead Full": false,
        "Combine Fire": false,
        "Evasive Maneuvers": false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Light Cannon": false,
      },
      shipActions: {
        move: false,
        attack: false,
        specialOrder: false,
      },
      isPendingDestruction: false,
    },

    destroyer: {
      factionName: "Star Reapers",
      shipId: "DE-ID:" + " " + new Date().getMilliseconds(5),
      type: "Destroyer",
      x: 100,
      y: 100,
      width: 104,
      height: 208,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image: "assets/ShipImages/SR/destroyer.png",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 8,
      hp: 8,
      damageThreshold: 4,
      threatLevel: 10,
      moveDistance: 60,
      weaponType: ["Medium Cannon"],
      firingArc: "Forward(90°)",
      weaponDamage: "1d10",
      weaponRange: 30,
      pointValue: 30,
      specialOrders: {
        "All Ahead Full": false,
        "Anti-Fighter Barrage": false,
        "Power Up Main Guns": false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Medium Cannon": false,
      },
      shipActions: {
        move: false,
        attack: false,
        specialOrder: false,
      },
      isPendingDestruction: false,
    },
    cruiser: {
      factionName: "Star Reapers",
      shipId: "CR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Cruiser",
      x: 100,
      y: 100,
      width: 123,
      height: 245,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image: "assets/ShipImages/SR/cruiser.png",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 12,
      hp: 12,
      damageThreshold: 6,
      threatLevel: 8,
      moveDistance: 50,
      weaponType: ["Heavy Cannon", "Plasma Cannon"],
      firingArc: "Forward(90°) \nPortside(90°)/Starboard(90°)",
      weaponDamage: "1d8 \n1d10",
      weaponRange: "30ft \n60ft",
      pointValue: 80,
      specialOrders: {
        "All Ahead Full": false,
        "All Systems Fire": false,
        "Reinforce Shields": false,
        Broadside: false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Heavy Cannon": false,
        "Plasma Cannon": false,
      },
      shipActions: {
        move: false,
        attack: false,
        specialOrder: false,
      },
      isPendingDestruction: false,
    },
    carrier: {
      factionName: "Star Reapers",
      shipId: "CA-ID:" + " " + new Date().getMilliseconds(5),
      type: "Carrier",
      x: 100,
      y: 100,
      width: 104,
      height: 208,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image: "assets/ShipImages/SR/carrier.png",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 14,
      hp: 14,
      damageThreshold: 7,
      threatLevel: 9,
      moveDistance: 40,
      weaponType: ["Missile Battery"],
      weaponStatus: { "Missile Battery": false },
      firingArc: "Forward(90°) \nAll(360°)",
      weaponDamage: "1d8 \n1d6",
      weaponRange: "30ft-120ft \n15ft-60ft",
      pointValue: 120,
      specialOrders: {
        "All Ahead Full": false,
        "Reinforce Shields": false,
        "Launch Fighters": false,
        "All Systems Fire": false,
      },
      hasBeenInteractedWith: false,
      capacity: 20,
      shipActions: {
        move: false,
        attack: false,
        specialOrder: false,
      },
      isPendingDestruction: false,
    },
    dreadnought: {
      factionName: "Star Reapers",
      shipId: "DR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Dreadnought",
      x: 100,
      y: 100,
      width: 218,
      height: 371,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image: "assets/ShipImages/SR/dread.png",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 30,
      hp: 30,
      damageThreshold: 4,
      threatLevel: 8,
      moveDistance: 30,
      weaponType: ["Ion Particle Beam", "Plasma Cannon", "350mm Railgun"],
      firingArc:
        "Forward(90°) \nPortside(90°)/Starboard(90°) \nForward(90°)/Aft(90°)",
      weaponDamage: "1d12\n1d10\n1d8",
      weaponRange: "30ft-60ft \n60ft \n30ft-120ft",
      pointValue: 240,
      specialOrders: {
        "All Ahead Full": false,
        "Reinforce Shields": false,
        "All Systems Fire": false,
        "Charge Ion Beam": false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Ion Particle Beam": false,
        "Plasma Cannon": false,
        "350mm Railgun": false,
      },
      shipActions: {
        move: false,
        attack: false,
        specialOrder: false,
      },
      isPendingDestruction: false,
    },
  },
  "Praxleon Empire": {
    fighter: {
      factionName: "Praxleon Empire",
      shipId: "FG-ID:" + " " + new Date().getMilliseconds(5),
      type: "Fighter",
      x: 100,
      y: 100,
      width: 68,
      height: 86,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image: "assets/ShipImages/PE/fighter.png",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 20,
      hp: 20,
      damageThreshold: 1,
      threatLevel: 15,
      moveDistance: 80,
      weaponType: ["Light Cannon"],
      firingArc: "Forward(90°)",
      weaponDamage: "1d4",
      weaponRange: 30,
      pointValue: 1,
      specialOrders: {
        "All Ahead Full": false,
        "Combine Fire": false,
        "Evasive Maneuvers": false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Light Cannon": false,
      },
      shipActions: {
        move: false,
        attack: false,
        specialOrder: false,
      },
      isPendingDestruction: false,
    },

    destroyer: {
      factionName: "Praxleon Empire",
      shipId: "DE-ID:" + " " + new Date().getMilliseconds(5),
      type: "Destroyer",
      x: 100,
      y: 100,
      width: 104,
      height: 208,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image: "assets/ShipImages/PE/destroyer.png",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 8,
      hp: 8,
      damageThreshold: 4,
      threatLevel: 10,
      moveDistance: 60,
      weaponType: ["Medium Cannon"],
      firingArc: "Forward(90°)",
      weaponDamage: "1d10",
      weaponRange: 30,
      pointValue: 30,
      specialOrders: {
        "All Ahead Full": false,
        "Anti-Fighter Barrage": false,
        "Power Up Main Guns": false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Medium Cannon": false,
      },
      shipActions: {
        move: false,
        attack: false,
        specialOrder: false,
      },
      isPendingDestruction: false,
    },
    cruiser: {
      factionName: "Praxleon Empire",
      shipId: "CR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Cruiser",
      x: 100,
      y: 100,
      width: 123,
      height: 245,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image: "assets/ShipImages/PE/cruiser.png",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 12,
      hp: 12,
      damageThreshold: 6,
      threatLevel: 8,
      moveDistance: 50,
      weaponType: ["Heavy Cannon", "Plasma Cannon"],
      firingArc: "Forward(90°) \nPortside(90°)/Starboard(90°)",
      weaponDamage: "1d8 \n1d10",
      weaponRange: "30ft \n60ft",
      pointValue: 80,
      specialOrders: {
        "All Ahead Full": false,
        "All Systems Fire": false,
        "Reinforce Shields": false,
        Broadside: false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Heavy Cannon": false,
        "Plasma Cannon": false,
      },
      shipActions: {
        move: false,
        attack: false,
        specialOrder: false,
      },
      isPendingDestruction: false,
    },
    carrier: {
      factionName: "Praxleon Empire",
      shipId: "CA-ID:" + " " + new Date().getMilliseconds(5),
      type: "Carrier",
      x: 100,
      y: 100,
      width: 104,
      height: 208,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image: "assets/ShipImages/PE/carrier.png",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 14,
      hp: 14,
      damageThreshold: 7,
      threatLevel: 9,
      moveDistance: 40,
      weaponType: ["Missle Battery"],
      weaponStatus: { "Missile Battery": false },
      firingArc: "Forward(90°) \nAll(360°)",
      weaponDamage: "1d8 \n1d6",
      weaponRange: "30ft-120ft \n15ft-60ft",
      pointValue: 120,
      specialOrders: {
        "All Ahead Full": false,
        "Reinforce Shields": false,
        "Launch Fighters": false,
        "All Systems Fire": false,
      },
      hasBeenInteractedWith: false,
      capacity: 20,
      shipActions: {
        move: false,
        attack: false,
        specialOrder: false,
      },
      isPendingDestruction: false,
    },
    dreadnought: {
      factionName: "Praxleon Empire",
      shipId: "DR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Dreadnought",
      x: 100,
      y: 100,
      width: 218,
      height: 371,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image: "assets/ShipImages/PE/dread.png",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 30,
      hp: 30,
      damageThreshold: 4,
      threatLevel: 8,
      moveDistance: 30,
      weaponType: ["Ion Particle Beam", "Plasma Cannon", "350mm Railgun"],
      firingArc:
        "Forward(90°) \nPortside(90°)/Starboard(90°) \nForward(90°)/Aft(90°)",
      weaponDamage: "1d12\n1d10\n1d8",
      weaponRange: "30ft-60ft \n60ft \n30ft-120ft",
      pointValue: 240,
      specialOrders: {
        "All Ahead Full": false,
        "Reinforce Shields": false,
        "All Systems Fire": false,
        "Charge Ion Beam": false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Ion Particle Beam": false,
        "Plasma Cannon": false,
        "350mm Railgun": false,
      },
      shipActions: {
        move: false,
        attack: false,
        specialOrder: false,
      },
      isPendingDestruction: false,
    },
  },
  "Synthon Syndicate": {
    fighter: {
      factionName: "Synthon Syndicate",
      shipId: "FG-ID:" + " " + new Date().getMilliseconds(5),
      type: "Fighter",
      x: 100,
      y: 100,
      width: 68,
      height: 86,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image: "assets/ShipImages/SS/fighter.png",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 20,
      hp: 20,
      damageThreshold: 1,
      threatLevel: 15,
      moveDistance: 80,
      weaponType: ["Light Cannon"],
      firingArc: "Forward(90°)",
      weaponDamage: "1d4",
      weaponRange: 30,
      pointValue: 1,
      specialOrders: {
        "All Ahead Full": false,
        "Combine Fire": false,
        "Evasive Maneuvers": false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Light Cannon": false,
      },
      shipActions: {
        move: false,
        attack: false,
        specialOrder: false,
      },
      isPendingDestruction: false,
    },

    destroyer: {
      factionName: "Synthon Syndicate",
      shipId: "DE-ID:" + " " + new Date().getMilliseconds(5),
      type: "Destroyer",
      x: 100,
      y: 100,
      width: 104,
      height: 208,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image: "assets/ShipImages/SS/destroyer.png",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 8,
      hp: 8,
      damageThreshold: 4,
      threatLevel: 10,
      moveDistance: 60,
      weaponType: ["Medium Cannon"],
      firingArc: "Forward(90°)",
      weaponDamage: "1d10",
      weaponRange: 30,
      pointValue: 30,
      specialOrders: {
        "All Ahead Full": false,
        "Anti-Fighter Barrage": false,
        "Power Up Main Guns": false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Medium Cannon": false,
      },
      shipActions: {
        move: false,
        attack: false,
        specialOrder: false,
      },
      isPendingDestruction: false,
    },
    cruiser: {
      factionName: "Synthon Syndicate",
      shipId: "CR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Cruiser",
      x: 100,
      y: 100,
      width: 123,
      height: 245,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image: "assets/ShipImages/SS/cruiser.png",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 12,
      hp: 12,
      damageThreshold: 6,
      threatLevel: 8,
      moveDistance: 50,
      weaponType: ["Heavy Cannon", "Plasma Cannon"],
      firingArc: "Forward(90°) \nPortside(90°)/Starboard(90°)",
      weaponDamage: "1d8 \n1d10",
      weaponRange: "30ft \n60ft",
      pointValue: 80,
      specialOrders: {
        "All Ahead Full": false,
        "All Systems Fire": false,
        "Reinforce Shields": false,
        Broadside: false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Heavy Cannon": false,
        "Plasma Cannon": false,
      },
      shipActions: {
        move: false,
        attack: false,
        specialOrder: false,
      },
      isPendingDestruction: false,
    },
    carrier: {
      factionName: "Synthon Syndicate",
      shipId: "CA-ID:" + " " + new Date().getMilliseconds(5),
      type: "Carrier",
      x: 100,
      y: 100,
      width: 104,
      height: 208,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image: "assets/ShipImages/SS/carrier.png",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 14,
      hp: 14,
      damageThreshold: 7,
      threatLevel: 9,
      moveDistance: 40,
      weaponType: ["Missile Battery"],
      weaponStatus: { "Missile Battery": false },
      firingArc: "Forward(90°) \nAll(360°)",
      weaponDamage: "1d8 \n1d6",
      weaponRange: "30ft-120ft \n15ft-60ft",
      pointValue: 120,
      specialOrders: {
        "All Ahead Full": false,
        "Reinforce Shields": false,
        "Launch Fighters": false,
        "All Systems Fire": false,
      },
      hasBeenInteractedWith: false,
      capacity: 20,
      shipActions: {
        move: false,
        attack: false,
        specialOrder: false,
      },
      isPendingDestruction: false,
    },
    dreadnought: {
      factionName: "Synthon Syndicate",
      shipId: "DR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Dreadnought",
      x: 100,
      y: 100,
      width: 218,
      height: 371,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image: "assets/ShipImages/SS/dread.png",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 30,
      hp: 30,
      damageThreshold: 4,
      threatLevel: 8,
      moveDistance: 30,
      weaponType: ["Ion Particle Beam", "Plasma Cannon", "350mm Railgun"],
      firingArc:
        "Forward(90°) \nPortside(90°)/Starboard(90°) \nForward(90°)/Aft(90°)",
      weaponDamage: "1d12\n1d10\n1d8",
      weaponRange: "30ft-60ft \n60ft \n30ft-120ft",
      pointValue: 240,
      specialOrders: {
        "All Ahead Full": false,
        "Reinforce Shields": false,
        "All Systems Fire": false,
        "Charge Ion Beam": false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Ion Particle Beam": false,
        "Plasma Cannon": false,
        "350mm Railgun": false,
      },
      shipActions: {
        move: false,
        attack: false,
        specialOrder: false,
      },
      isPendingDestruction: false,
    },
  },
  "The Union": {
    fighter: {
      factionName: "The Union",
      shipId: "FG-ID:" + " " + new Date().getMilliseconds(5),
      type: "Fighter",
      x: 100,
      y: 100,
      width: 68,
      height: 86,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image: "assets/ShipImages/UN/fighter.png",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 20,
      hp: 20,
      damageThreshold: 1,
      threatLevel: 15,
      moveDistance: 80,
      weaponType: ["Light Cannon"],
      firingArc: "Forward(90°)",
      weaponDamage: "1d4",
      weaponRange: 30,
      pointValue: 1,
      specialOrders: {
        "All Ahead Full": false,
        "Combine Fire": false,
        "Evasive Maneuvers": false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Light Cannon": false,
      },
      shipActions: {
        move: false,
        attack: false,
        specialOrder: false,
      },
      isPendingDestruction: false,
    },

    destroyer: {
      factionName: "The Union",
      shipId: "DE-ID:" + " " + new Date().getMilliseconds(5),
      type: "Destroyer",
      x: 100,
      y: 100,
      width: 104,
      height: 208,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image: "assets/ShipImages/UN/destroyer.png",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 8,
      hp: 8,
      damageThreshold: 4,
      threatLevel: 10,
      moveDistance: 60,
      weaponType: ["Medium Cannon"],
      firingArc: "Forward(90°)",
      weaponDamage: "1d10",
      weaponRange: 30,
      pointValue: 30,
      specialOrders: {
        "All Ahead Full": false,
        "Anti-Fighter Barrage": false,
        "Power Up Main Guns": false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Medium Cannon": false,
      },
      shipActions: {
        move: false,
        attack: false,
        specialOrder: false,
      },
      isPendingDestruction: false,
    },
    cruiser: {
      factionName: "The Union",
      shipId: "CR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Cruiser",
      x: 100,
      y: 100,
      width: 123,
      height: 245,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image: "assets/ShipImages/UN/cruiser.png",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 12,
      hp: 12,
      damageThreshold: 6,
      threatLevel: 8,
      moveDistance: 50,
      weaponType: ["Heavy Cannon", "Plasma Cannon"],
      firingArc: "Forward(90°) \nPortside(90°)/Starboard(90°)",
      weaponDamage: "1d8 \n1d10",
      weaponRange: "30ft \n60ft",
      pointValue: 80,
      specialOrders: {
        "All Ahead Full": false,
        "All Systems Fire": false,
        "Reinforce Shields": false,
        Broadside: false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Heavy Cannon": false,
        "Plasma Cannon": false,
      },
      shipActions: {
        move: false,
        attack: false,
        specialOrder: false,
      },
      isPendingDestruction: false,
    },
    carrier: {
      factionName: "The Union",
      shipId: "CA-ID:" + " " + new Date().getMilliseconds(5),
      type: "Carrier",
      x: 100,
      y: 100,
      width: 104,
      height: 208,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image: "assets/ShipImages/UN/carrier.png",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 14,
      hp: 14,
      damageThreshold: 7,
      threatLevel: 9,
      moveDistance: 40,
      weaponType: ["=Missile Battery"],
      weaponStatus: { "Missile Battery": false },
      firingArc: "Forward(90°) \nAll(360°)",
      weaponDamage: "1d8 \n1d6",
      weaponRange: "30ft-120ft \n15ft-60ft",
      pointValue: 120,
      specialOrders: {
        "All Ahead Full": false,
        "Reinforce Shields": false,
        "Launch Fighters": false,
        "All Systems Fire": false,
      },
      hasBeenInteractedWith: false,
      capacity: 20,
      shipActions: {
        move: false,
        attack: false,
        specialOrder: false,
      },
      isPendingDestruction: false,
    },
    dreadnought: {
      factionName: "The Union",
      shipId: "DR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Dreadnought",
      x: 100,
      y: 100,
      width: 218,
      height: 371,
      isSelected: false,

      isToggled: false,
      rotation_angle: 0,
      image: "assets/ShipImages/UN/dread.png",
      maxHP: 30,
      hp: 30,
      damageThreshold: 4,
      threatLevel: 8,
      moveDistance: 30,
      weaponType: ["Ion Particle Beam", "Plasma Cannon", "350mm Railgun"],
      firingArc:
        "Forward(90°) \nPortside(90°)/Starboard(90°) \nForward(90°)/Aft(90°)",
      weaponDamage: "1d12\n1d10\n1d8",
      weaponRange: "30ft-60ft \n60ft \n30ft-120ft",
      pointValue: 240,
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      specialOrders: {
        "All Ahead Full": false,
        "Reinforce Shields": false,
        "All Systems Fire": false,
        "Charge Ion Beam": false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Ion Particle Beam": false,
        "Plasma Cannon": false,
        "350mm Railgun": false,
      },
      shipActions: {
        move: false,
        attack: false,
        specialOrder: false,
      },
      isPendingDestruction: false,
    },
  },
};
