export const shipObject = {
  "Nova Raiders": {
    fighter: {
      factionName: "Nova Raiders",
      shipId: "FG-ID:" + " " + new Date().getMilliseconds(5),
      type: "Fighter",
      x: 100,
      y: 100,
      width: 68,
      height: 86,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Faction7%2FChatGPT%20Image%20May%2026%2C%202025%2C%2002_41_31%20PM.png?alt=media&token=6705c15c-f37a-4188-81d8-3b7e8d18ce3a",

      maxHP: 20,
      hp: 20,
      damageThreshold: 1,
      threatLevel: 15,
      moveDistance: 80,
      weaponType: ["Light Cannon"],
      firingArc: "Forward(90°)",
      weaponDamage: "1d4",
      weaponRange: 30,
      pointValue: 1,
      specialOrders: {
        "Full Throttle": false,
        "Combine Fire": false,
        "Evasive Maneuvers": false,
      },
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Light Cannon": false,
      },
    },

    destroyer: {
      factionName: "Nova Raiders",
      shipId: "DE-ID:" + " " + new Date().getMilliseconds(5),
      type: "Destroyer",
      x: 100,
      y: 100,

      width: 104,
      height: 208,
      isSelected: false,

      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Faction7%2FChatGPT%20Image%20May%2026%2C%202025%2C%2002_27_22%20PM.png?alt=media&token=ba3c3ad0-09e5-40ff-8f1b-082e8df13706",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 8,
      hp: 8,
      damageThreshold: 4,
      threatLevel: 10,
      moveDistance: 60,
      weaponType: ["Medium Cannon"],
      firingArc: "Forward(90°)",
      weaponDamage: "1d10",
      weaponRange: 30,
      pointValue: 30,
      specialOrders: {
        "Full Throttle": false,
        "Anti-Fighter Barrage": false,
        "Power Up Main Guns": false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Medium Cannon": false,
      },
    },
    cruiser: {
      factionName: "Nova Raiders",
      shipId: "CR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Cruiser",
      x: 100,
      y: 100,
      width: 123,
      height: 245,
      isSelected: false,
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Faction7%2FChatGPT%20Image%20May%2026%2C%202025%2C%2002_45_37%20PM.png?alt=media&token=8540477f-292d-48e5-9d51-8b19e818620f",
      maxHP: 12,
      hp: 12,
      damageThreshold: 6,
      threatLevel: 8,
      moveDistance: 50,
      weaponType: ["Heavy Cannon", "Plasma Cannon"],
      firingArc: "Forward(90°) \nPortside(90°)/Starboard(90°)",
      weaponDamage: "1d8 \n1d10",
      weaponRange: "30ft \n60ft",
      pointValue: 80,
      specialOrders: {
        "Full Throttle": false,
        "All Systems Fire": false,
        "Reinforce Shields": false,
        Broadside: false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Heavy Cannon": false,
        "Plasma Cannon": false,
      },
    },
    carrier: {
      factionName: "Nova Raiders",
      shipId: "CA-ID:" + " " + new Date().getMilliseconds(5),
      type: "Carrier",
      x: 100,
      y: 100,
      width: 104,
      height: 208,
      isSelected: false,

      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Faction7%2FChatGPT%20Image%20May%2026%2C%202025%2C%2002_43_06%20PM.png?alt=media&token=40f7b236-0ebd-48c8-8d45-bfcfec7e9f4c",
      maxHP: 14,
      hp: 14,
      damageThreshold: 7,
      threatLevel: 9,
      moveDistance: 40,
      weaponType: ["Missile Battery"],
      weaponStatus: { "Missile Battery": false },
      firingArc: "Forward(90°) \nAll(360°)",
      weaponDamage: "1d8 \n1d6",
      weaponRange: "30ft-120ft \n15ft-60ft",
      pointValue: 120,
      specialOrders: {
        "Full Throttle": false,
        "Reinforce Shields": false,
        "Launch Fighters": false,
        "All Systems Fire": false,
      },
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      hasBeenInteractedWith: false,
      maxCapacity: 20,
      capacity: 20,
    },
    dreadnought: {
      factionName: "Nova Raiders",
      shipId: "DR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Dreadnought",
      x: 100,
      y: 100,
      width: 218,
      height: 371,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Faction7%2FChatGPT%20Image%20May%2026%2C%202025%2C%2002_29_52%20PM.png?alt=media&token=4477e2e4-51b0-4acc-bdc0-900cf5e48898",
      maxHP: 30,
      hp: 30,
      damageThreshold: 4,
      threatLevel: 8,
      moveDistance: 30,
      weaponType: ["Ion Particle Beam", "Plasma Cannon", "350mm Railgun"],
      firingArc:
        "Forward(90°) \nPortside(90°)/Starboard(90°) \nForward(90°)/Aft(90°)",
      weaponDamage: "1d12\n1d10\n1d8",
      weaponRange: "30ft-60ft \n60ft \n30ft-120ft",
      pointValue: 240,
      specialOrders: {
        "Full Throttle": false,
        "Reinforce Shields": false,
        "All Systems Fire": false,
        "Charge Ion Beam": false,
      },
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Ion Particle Beam": false,
        "Plasma Cannon": false,
        "350mm Railgun": false,
      },
    },
  },
  "The Zyrrians": {
    fighter: {
      factionName: "The Zyrrians",
      shipId: "FG-ID:" + " " + new Date().getMilliseconds(5),
      type: "Fighter",
      x: 100,
      y: 100,
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      width: 68,
      height: 86,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Faction4%2FChatGPT%20Image%20May%2026%2C%202025%2C%2003_48_02%20PM.png?alt=media&token=8ad99515-edc9-40da-b5de-d6349150be8c",
      maxHP: 20,
      hp: 20,
      damageThreshold: 1,
      threatLevel: 15,
      moveDistance: 80,
      weaponType: ["Light Cannon"],
      firingArc: "Forward(90°)",
      weaponDamage: "1d4",
      weaponRange: 30,
      pointValue: 1,
      specialOrders: {
        "Full Throttle": false,
        "Combine Fire": false,
        "Evasive Maneuvers": false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Light Cannon": false,
      },
    },

    destroyer: {
      factionName: "The Zyrrians",
      shipId: "DE-ID:" + " " + new Date().getMilliseconds(5),
      type: "Destroyer",
      x: 100,
      y: 100,
      width: 104,
      height: 208,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Faction4%2FChatGPT%20Image%20May%2026%2C%202025%2C%2004_06_44%20PM.png?alt=media&token=7977b803-9e3f-4ee5-8ca1-d89d1e254b16",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 8,
      hp: 8,
      damageThreshold: 4,
      threatLevel: 10,
      moveDistance: 60,
      weaponType: ["Medium Cannon"],
      firingArc: "Forward(90°)",
      weaponDamage: "1d10",
      weaponRange: 30,
      pointValue: 30,
      specialOrders: {
        "Full Throttle": false,
        "Anti-Fighter Barrage": false,
        "Power Up Main Guns": false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Medium Cannon": false,
      },
    },
    cruiser: {
      factionName: "The Zyrrians",
      shipId: "CR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Cruiser",
      x: 100,
      y: 100,
      width: 123,
      height: 245,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Faction4%2FChatGPT%20Image%20May%2026%2C%202025%2C%2003_59_57%20PM.png?alt=media&token=2e74cfcb-02ac-4707-9d65-32e988f3bf4f",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 12,
      hp: 12,
      damageThreshold: 6,
      threatLevel: 8,
      moveDistance: 50,
      weaponType: ["Heavy Cannon", "Plasma Cannon"],
      firingArc: "Forward(90°) \nPortside(90°)/Starboard(90°)",
      weaponDamage: "1d8 \n1d10",
      weaponRange: "30ft \n60ft",
      pointValue: 80,
      specialOrders: {
        "Full Throttle": false,
        "All Systems Fire": false,
        "Reinforce Shields": false,
        Broadside: false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Heavy Cannon": false,
        "Plasma Cannon": false,
      },
    },
    carrier: {
      factionName: "The Zyrrians",
      shipId: "CA-ID:" + " " + new Date().getMilliseconds(5),
      type: "Carrier",
      x: 100,
      y: 100,
      width: 104,
      height: 208,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Faction4%2FChatGPT%20Image%20May%2026%2C%202025%2C%2004_03_11%20PM.png?alt=media&token=854ca323-8b17-49d2-ac15-216c4791e89d",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 14,
      hp: 14,
      damageThreshold: 7,
      threatLevel: 9,
      moveDistance: 40,
      weaponType: ["Missile Battery"],
      weaponStatus: { "Missile Battery": false },
      firingArc: "Forward(90°) \nAll(360°)",
      weaponDamage: "1d8 \n1d6",
      weaponRange: "30ft-120ft \n15ft-60ft",
      pointValue: 120,
      specialOrders: {
        "Full Throttle": false,
        "Reinforce Shields": false,
        "Launch Fighters": false,
        "All Systems Fire": false,
      },
      hasBeenInteractedWith: false,
      maxCapacity: 20,
      capacity: 20,
    },
    dreadnought: {
      factionName: "The Zyrrians",
      shipId: "DR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Dreadnought",
      x: 100,
      y: 100,
      width: 218,
      height: 371,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Faction4%2FChatGPT%20Image%20May%2026%2C%202025%2C%2003_45_32%20PM.png?alt=media&token=c04082eb-c0e0-4a1c-b028-6d0533c0b0e0",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 30,
      hp: 30,
      damageThreshold: 4,
      threatLevel: 8,
      moveDistance: 30,
      weaponType: ["Ion Particle Beam", "Plasma Cannon", "350mm Railgun"],
      firingArc:
        "Forward(90°) \nPortside(90°)/Starboard(90°) \nForward(90°)/Aft(90°)",
      weaponDamage: "1d12\n1d10\n1d8",
      weaponRange: "30ft-60ft \n60ft \n30ft-120ft",
      pointValue: 240,
      specialOrders: {
        "Full Throttle": false,
        "Reinforce Shields": false,
        "All Systems Fire": false,
        "Charge Ion Beam": false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Ion Particle Beam": false,
        "Plasma Cannon": false,
        "350mm Railgun": false,
      },
    },
  },
  "Voidborn Marauders": {
    fighter: {
      factionName: "Voidborn Marauders",
      shipId: "FG-ID:" + " " + new Date().getMilliseconds(5),
      type: "Fighter",
      x: 100,
      y: 100,
      width: 68,
      height: 86,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Faction5%2FChatGPT%20Image%20May%2026%2C%202025%2C%2012_33_05%20PM.png?alt=media&token=56510c8c-1d9e-4dfb-9b5a-53bbe6af752d",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 20,
      hp: 20,
      damageThreshold: 1,
      threatLevel: 15,
      moveDistance: 80,
      weaponType: ["Light Cannon"],
      firingArc: "Forward(90°)",
      weaponDamage: "1d4",
      weaponRange: 30,
      pointValue: 1,
      specialOrders: {
        "Full Throttle": false,
        "Combine Fire": false,
        "Evasive Maneuvers": false,
      },
      weaponStatus: {
        "Light Cannon": false,
      },
    },

    destroyer: {
      factionName: "Voidborn Marauders",
      shipId: "DE-ID:" + " " + new Date().getMilliseconds(5),
      type: "Destroyer",
      x: 100,
      y: 100,
      width: 104,
      height: 208,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Faction5%2FChatGPT%20Image%20May%2026%2C%202025%2C%2012_13_01%20PM.png?alt=media&token=56d7049f-d1a5-43d6-a15b-815c8308874b",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 8,
      hp: 8,
      damageThreshold: 4,
      threatLevel: 10,
      moveDistance: 60,
      weaponType: ["Medium Cannon"],
      firingArc: "Forward(90°)",
      weaponDamage: "1d10",
      weaponRange: 30,
      pointValue: 30,
      specialOrders: {
        "Full Throttle": false,
        "Anti-Fighter Barrage": false,
        "Power Up Main Guns": false,
      },
      weaponStatus: {
        "Medium Cannon": false,
      },
    },
    cruiser: {
      factionName: "Voidborn Marauders",
      shipId: "CR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Cruiser",
      x: 100,
      y: 100,
      width: 123,
      height: 245,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Faction5%2FChatGPT%20Image%20May%2026%2C%202025%2C%2012_30_01%20PM.png?alt=media&token=4ac46b54-f444-47ac-be4a-d119c265e2b1",
      maxHP: 12,
      hp: 12,
      damageThreshold: 6,
      threatLevel: 8,
      moveDistance: 50,
      weaponType: ["Heavy Cannon", "Plasma Cannon"],
      firingArc: "Forward(90°) \nPortside(90°)/Starboard(90°)",
      weaponDamage: "1d8 \n1d10",
      weaponRange: "30ft \n60ft",
      pointValue: 80,
      specialOrders: {
        "Full Throttle": false,
        "All Systems Fire": false,
        "Reinforce Shields": false,
        Broadside: false,
      },
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      weaponStatus: {
        "Heavy Cannon": false,
        "Plasma Cannon": false,
      },
    },
    carrier: {
      factionName: "Voidborn Marauders",
      shipId: "CA-ID:" + " " + new Date().getMilliseconds(5),
      type: "Carrier",
      x: 100,
      y: 100,
      width: 104,
      height: 208,
      isSelected: false,

      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Faction5%2FChatGPT%20Image%20May%2026%2C%202025%2C%2011_44_40%20AM.png?alt=media&token=2426e3a1-b1ff-4aa0-a890-379cbdc85c25",
      maxHP: 14,
      hp: 14,
      damageThreshold: 7,
      threatLevel: 9,
      moveDistance: 40,
      firingArc: "Forward(90°) \nAll(360°)",
      weaponDamage: "1d8 \n1d6",
      weaponRange: "30ft-120ft \n15ft-60ft",
      pointValue: 120,
      specialOrders: {
        "Full Throttle": false,
        "Reinforce Shields": false,
        "Launch Fighters": false,
        "All Systems Fire": false,
      },
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      weaponType: ["Missile Battery"],
      weaponStatus: { "Missile Battery": false },
      maxCapacity: 20,
      capacity: 20,
    },
    dreadnought: {
      factionName: "Voidborn Marauders",
      shipId: "DR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Dreadnought",
      x: 100,
      y: 100,
      width: 218,
      height: 371,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Faction5%2FChatGPT%20Image%20May%2026%2C%202025%2C%2009_34_15%20AM.png?alt=media&token=ca5c3322-3265-4476-8cfb-67619335f208",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 30,
      hp: 30,
      damageThreshold: 4,
      threatLevel: 8,
      moveDistance: 30,
      weaponType: ["Ion Particle Beam", "Plasma Cannon", "350mm Railgun"],
      firingArc:
        "Forward(90°) \nPortside(90°)/Starboard(90°) \nForward(90°)/Aft(90°)",
      weaponDamage: "1d12\n1d10\n1d8",
      weaponRange: "30ft-60ft \n60ft \n30ft-120ft",
      pointValue: 240,
      specialOrders: {
        "Full Throttle": false,
        "Reinforce Shields": false,
        "All Systems Fire": false,
        "Charge Ion Beam": false,
      },
      moveDistanceBonus: 0,
      weaponStatus: {
        "Ion Particle Beam": false,
        "Plasma Cannon": false,
        "350mm Railgun": false,
      },
    },
  },
  "Star Reapers": {
    fighter: {
      factionName: "Star Reapers",
      shipId: "FG-ID:" + " " + new Date().getMilliseconds(5),
      type: "Fighter",
      x: 100,
      y: 100,
      width: 68,
      height: 86,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Faction1%2FChatGPT%20Image%20May%2026%2C%202025%2C%2009_36_52%20AM.png?alt=media&token=e8c35b22-dc3c-4111-909a-b2e8fb15f5a7",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 20,
      hp: 20,
      damageThreshold: 1,
      threatLevel: 15,
      moveDistance: 80,
      weaponType: ["Light Cannon"],
      firingArc: "Forward(90°)",
      weaponDamage: "1d4",
      weaponRange: 30,
      pointValue: 1,
      specialOrders: {
        "Full Throttle": false,
        "Combine Fire": false,
        "Evasive Maneuvers": false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Light Cannon": false,
      },
    },

    destroyer: {
      factionName: "Star Reapers",
      shipId: "DE-ID:" + " " + new Date().getMilliseconds(5),
      type: "Destroyer",
      x: 100,
      y: 100,
      width: 104,
      height: 208,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Faction1%2FChatGPT%20Image%20May%2026%2C%202025%2C%2009_30_37%20AM.png?alt=media&token=442d40a1-ce0e-4dd7-9dcc-36feff1d9823",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 8,
      hp: 8,
      damageThreshold: 4,
      threatLevel: 10,
      moveDistance: 60,
      weaponType: ["Medium Cannon"],
      firingArc: "Forward(90°)",
      weaponDamage: "1d10",
      weaponRange: 30,
      pointValue: 30,
      specialOrders: {
        "Full Throttle": false,
        "Anti-Fighter Barrage": false,
        "Power Up Main Guns": false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Medium Cannon": false,
      },
    },
    cruiser: {
      factionName: "Star Reapers",
      shipId: "CR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Cruiser",
      x: 100,
      y: 100,
      width: 123,
      height: 245,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Faction1%2FChatGPT%20Image%20May%2026%2C%202025%2C%2009_09_32%20AM.png?alt=media&token=e2807265-ef5e-40c6-b448-75f96a41feb3",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 12,
      hp: 12,
      damageThreshold: 6,
      threatLevel: 8,
      moveDistance: 50,
      weaponType: ["Heavy Cannon", "Plasma Cannon"],
      firingArc: "Forward(90°) \nPortside(90°)/Starboard(90°)",
      weaponDamage: "1d8 \n1d10",
      weaponRange: "30ft \n60ft",
      pointValue: 80,
      specialOrders: {
        "Full Throttle": false,
        "All Systems Fire": false,
        "Reinforce Shields": false,
        Broadside: false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Heavy Cannon": false,
        "Plasma Cannon": false,
      },
    },
    carrier: {
      factionName: "Star Reapers",
      shipId: "CA-ID:" + " " + new Date().getMilliseconds(5),
      type: "Carrier",
      x: 100,
      y: 100,
      width: 104,
      height: 208,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Faction1%2FChatGPT%20Image%20May%2026%2C%202025%2C%2009_27_35%20AM.png?alt=media&token=62ef9303-5904-4a42-bb8d-fe14f00551e0",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 14,
      hp: 14,
      damageThreshold: 7,
      threatLevel: 9,
      moveDistance: 40,
      weaponType: ["Missile Battery"],
      weaponStatus: { "Missile Battery": false },
      firingArc: "Forward(90°) \nAll(360°)",
      weaponDamage: "1d8 \n1d6",
      weaponRange: "30ft-120ft \n15ft-60ft",
      pointValue: 120,
      specialOrders: {
        "Full Throttle": false,
        "Reinforce Shields": false,
        "Launch Fighters": false,
        "All Systems Fire": false,
      },
      hasBeenInteractedWith: false,
      maxCapacity: 20,
      capacity: 20,
    },
    dreadnought: {
      factionName: "Star Reapers",
      shipId: "DR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Dreadnought",
      x: 100,
      y: 100,
      width: 218,
      height: 371,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Faction1%2FChatGPT%20Image%20May%2026%2C%202025%2C%2009_06_26%20AM.png?alt=media&token=9e5cc2fe-d83c-4091-8f17-b3c5c46bbc96",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 30,
      hp: 30,
      damageThreshold: 4,
      threatLevel: 8,
      moveDistance: 30,
      weaponType: ["Ion Particle Beam", "Plasma Cannon", "350mm Railgun"],
      firingArc:
        "Forward(90°) \nPortside(90°)/Starboard(90°) \nForward(90°)/Aft(90°)",
      weaponDamage: "1d12\n1d10\n1d8",
      weaponRange: "30ft-60ft \n60ft \n30ft-120ft",
      pointValue: 240,
      specialOrders: {
        "Full Throttle": false,
        "Reinforce Shields": false,
        "All Systems Fire": false,
        "Charge Ion Beam": false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Ion Particle Beam": false,
        "Plasma Cannon": false,
        "350mm Railgun": false,
      },
    },
  },
  "Praxleon Empire": {
    fighter: {
      factionName: "Praxleon Empire",
      shipId: "FG-ID:" + " " + new Date().getMilliseconds(5),
      type: "Fighter",
      x: 100,
      y: 100,
      width: 68,
      height: 86,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Faction2%2FChatGPT%20Image%20May%2026%2C%202025%2C%2011_05_34%20AM.png?alt=media&token=39cf58b4-98f9-43ed-aec0-53ae887f4fdf",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 20,
      hp: 20,
      damageThreshold: 1,
      threatLevel: 15,
      moveDistance: 80,
      weaponType: ["Light Cannon"],
      firingArc: "Forward(90°)",
      weaponDamage: "1d4",
      weaponRange: 30,
      pointValue: 1,
      specialOrders: {
        "Full Throttle": false,
        "Combine Fire": false,
        "Evasive Maneuvers": false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Light Cannon": false,
      },
    },

    destroyer: {
      factionName: "Praxleon Empire",
      shipId: "DE-ID:" + " " + new Date().getMilliseconds(5),
      type: "Destroyer",
      x: 100,
      y: 100,
      width: 104,
      height: 208,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Faction2%2FChatGPT%20Image%20May%2026%2C%202025%2C%2011_35_07%20AM.png?alt=media&token=b3877058-7e8d-419c-924d-c0e38be57800",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 8,
      hp: 8,
      damageThreshold: 4,
      threatLevel: 10,
      moveDistance: 60,
      weaponType: ["Medium Cannon"],
      firingArc: "Forward(90°)",
      weaponDamage: "1d10",
      weaponRange: 30,
      pointValue: 30,
      specialOrders: {
        "Full Throttle": false,
        "Anti-Fighter Barrage": false,
        "Power Up Main Guns": false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Medium Cannon": false,
      },
    },
    cruiser: {
      factionName: "Praxleon Empire",
      shipId: "CR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Cruiser",
      x: 100,
      y: 100,
      width: 123,
      height: 245,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Faction2%2FChatGPT%20Image%20May%2026%2C%202025%2C%2011_29_55%20AM.png?alt=media&token=458c3522-e757-4d7f-ac59-66877fd1f6e5",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 12,
      hp: 12,
      damageThreshold: 6,
      threatLevel: 8,
      moveDistance: 50,
      weaponType: ["Heavy Cannon", "Plasma Cannon"],
      firingArc: "Forward(90°) \nPortside(90°)/Starboard(90°)",
      weaponDamage: "1d8 \n1d10",
      weaponRange: "30ft \n60ft",
      pointValue: 80,
      specialOrders: {
        "Full Throttle": false,
        "All Systems Fire": false,
        "Reinforce Shields": false,
        Broadside: false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Heavy Cannon": false,
        "Plasma Cannon": false,
      },
    },
    carrier: {
      factionName: "Praxleon Empire",
      shipId: "CA-ID:" + " " + new Date().getMilliseconds(5),
      type: "Carrier",
      x: 100,
      y: 100,
      width: 104,
      height: 208,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Faction2%2FChatGPT%20Image%20May%2026%2C%202025%2C%2011_24_34%20AM.png?alt=media&token=6ba82900-9e66-4a7b-a5f6-329e240ced37",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 14,
      hp: 14,
      damageThreshold: 7,
      threatLevel: 9,
      moveDistance: 40,
      weaponType: ["Missle Battery"],
      weaponStatus: { "Missile Battery": false },
      firingArc: "Forward(90°) \nAll(360°)",
      weaponDamage: "1d8 \n1d6",
      weaponRange: "30ft-120ft \n15ft-60ft",
      pointValue: 120,
      specialOrders: {
        "Full Throttle": false,
        "Reinforce Shields": false,
        "Launch Fighters": false,
        "All Systems Fire": false,
      },
      hasBeenInteractedWith: false,
      maxCapacity: 20,
      capacity: 20,
    },
    dreadnought: {
      factionName: "Praxleon Empire",
      shipId: "DR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Dreadnought",
      x: 100,
      y: 100,
      width: 218,
      height: 371,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Faction2%2FChatGPT%20Image%20May%2026%2C%202025%2C%2011_11_48%20AM.png?alt=media&token=61615d00-2131-4288-b09a-d2be847e9fb4",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 30,
      hp: 30,
      damageThreshold: 4,
      threatLevel: 8,
      moveDistance: 30,
      weaponType: ["Ion Particle Beam", "Plasma Cannon", "350mm Railgun"],
      firingArc:
        "Forward(90°) \nPortside(90°)/Starboard(90°) \nForward(90°)/Aft(90°)",
      weaponDamage: "1d12\n1d10\n1d8",
      weaponRange: "30ft-60ft \n60ft \n30ft-120ft",
      pointValue: 240,
      specialOrders: {
        "Full Throttle": false,
        "Reinforce Shields": false,
        "All Systems Fire": false,
        "Charge Ion Beam": false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Ion Particle Beam": false,
        "Plasma Cannon": false,
        "350mm Railgun": false,
      },
    },
  },
  "Synthon Syndicate": {
    fighter: {
      factionName: "Synthon Syndicate",
      shipId: "FG-ID:" + " " + new Date().getMilliseconds(5),
      type: "Fighter",
      x: 100,
      y: 100,
      width: 68,
      height: 86,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Faction3%2FChatGPT%20Image%20May%2027%2C%202025%2C%2009_59_00%20AM.png?alt=media&token=f95a0054-cf1b-4ce9-b485-54ead870fe2f",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 20,
      hp: 20,
      damageThreshold: 1,
      threatLevel: 15,
      moveDistance: 80,
      weaponType: ["Light Cannon"],
      firingArc: "Forward(90°)",
      weaponDamage: "1d4",
      weaponRange: 30,
      pointValue: 1,
      specialOrders: {
        "Full Throttle": false,
        "Combine Fire": false,
        "Evasive Maneuvers": false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Light Cannon": false,
      },
    },

    destroyer: {
      factionName: "Synthon Syndicate",
      shipId: "DE-ID:" + " " + new Date().getMilliseconds(5),
      type: "Destroyer",
      x: 100,
      y: 100,
      width: 104,
      height: 208,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Faction3%2FChatGPT%20Image%20May%2027%2C%202025%2C%2009_53_48%20AM.png?alt=media&token=e4745f68-752d-49fb-b8c9-c5bd9afe1f21",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 8,
      hp: 8,
      damageThreshold: 4,
      threatLevel: 10,
      moveDistance: 60,
      weaponType: ["Medium Cannon"],
      firingArc: "Forward(90°)",
      weaponDamage: "1d10",
      weaponRange: 30,
      pointValue: 30,
      specialOrders: {
        "Full Throttle": false,
        "Anti-Fighter Barrage": false,
        "Power Up Main Guns": false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Medium Cannon": false,
      },
    },
    cruiser: {
      factionName: "Synthon Syndicate",
      shipId: "CR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Cruiser",
      x: 100,
      y: 100,
      width: 123,
      height: 245,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Faction3%2FChatGPT%20Image%20May%2027%2C%202025%2C%2009_51_53%20AM.png?alt=media&token=aef2db7d-b127-4c47-bdcb-e9f0044c5817",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 12,
      hp: 12,
      damageThreshold: 6,
      threatLevel: 8,
      moveDistance: 50,
      weaponType: ["Heavy Cannon", "Plasma Cannon"],
      firingArc: "Forward(90°) \nPortside(90°)/Starboard(90°)",
      weaponDamage: "1d8 \n1d10",
      weaponRange: "30ft \n60ft",
      pointValue: 80,
      specialOrders: {
        "Full Throttle": false,
        "All Systems Fire": false,
        "Reinforce Shields": false,
        Broadside: false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Heavy Cannon": false,
        "Plasma Cannon": false,
      },
    },
    carrier: {
      factionName: "Synthon Syndicate",
      shipId: "CA-ID:" + " " + new Date().getMilliseconds(5),
      type: "Carrier",
      x: 100,
      y: 100,
      width: 104,
      height: 208,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Faction3%2FChatGPT%20Image%20May%2027%2C%202025%2C%2009_48_23%20AM.png?alt=media&token=506b482a-fcef-4dd5-8bf9-22b04a19814e",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 14,
      hp: 14,
      damageThreshold: 7,
      threatLevel: 9,
      moveDistance: 40,
      weaponType: ["Missile Battery"],
      weaponStatus: { "Missile Battery": false },
      firingArc: "Forward(90°) \nAll(360°)",
      weaponDamage: "1d8 \n1d6",
      weaponRange: "30ft-120ft \n15ft-60ft",
      pointValue: 120,
      specialOrders: {
        "Full Throttle": false,
        "Reinforce Shields": false,
        "Launch Fighters": false,
        "All Systems Fire": false,
      },
      hasBeenInteractedWith: false,
      maxCapacity: 20,
      capacity: 20,
    },
    dreadnought: {
      factionName: "Synthon Syndicate",
      shipId: "DR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Dreadnought",
      x: 100,
      y: 100,
      width: 218,
      height: 371,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Faction3%2FChatGPT%20Image%20May%2027%2C%202025%2C%2009_36_21%20AM.png?alt=media&token=6deda667-cc6d-49fa-8805-2dc75273e847",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 30,
      hp: 30,
      damageThreshold: 4,
      threatLevel: 8,
      moveDistance: 30,
      weaponType: ["Ion Particle Beam", "Plasma Cannon", "350mm Railgun"],
      firingArc:
        "Forward(90°) \nPortside(90°)/Starboard(90°) \nForward(90°)/Aft(90°)",
      weaponDamage: "1d12\n1d10\n1d8",
      weaponRange: "30ft-60ft \n60ft \n30ft-120ft",
      pointValue: 240,
      specialOrders: {
        "Full Throttle": false,
        "Reinforce Shields": false,
        "All Systems Fire": false,
        "Charge Ion Beam": false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Ion Particle Beam": false,
        "Plasma Cannon": false,
        "350mm Railgun": false,
      },
    },
  },
  "The Union": {
    fighter: {
      factionName: "The Union",
      shipId: "FG-ID:" + " " + new Date().getMilliseconds(5),
      type: "Fighter",
      x: 100,
      y: 100,
      width: 68,
      height: 86,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Faction6%2FChatGPT%20Image%20May%2026%2C%202025%2C%2010_30_43%20AM.png?alt=media&token=ce2b461a-9b7e-4e51-acbb-4ec860693898",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 20,
      hp: 20,
      damageThreshold: 1,
      threatLevel: 15,
      moveDistance: 80,
      weaponType: ["Light Cannon"],
      firingArc: "Forward(90°)",
      weaponDamage: "1d4",
      weaponRange: 30,
      pointValue: 1,
      specialOrders: {
        "Full Throttle": false,
        "Combine Fire": false,
        "Evasive Maneuvers": false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Light Cannon": false,
      },
    },

    destroyer: {
      factionName: "The Union",
      shipId: "DE-ID:" + " " + new Date().getMilliseconds(5),
      type: "Destroyer",
      x: 100,
      y: 100,
      width: 104,
      height: 208,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Faction6%2FChatGPT%20Image%20May%2026%2C%202025%2C%2010_20_03%20AM.png?alt=media&token=862a1576-a33a-47c5-ab58-5f3812f56286",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 8,
      hp: 8,
      damageThreshold: 4,
      threatLevel: 10,
      moveDistance: 60,
      weaponType: ["Medium Cannon"],
      firingArc: "Forward(90°)",
      weaponDamage: "1d10",
      weaponRange: 30,
      pointValue: 30,
      specialOrders: {
        "Full Throttle": false,
        "Anti-Fighter Barrage": false,
        "Power Up Main Guns": false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Medium Cannon": false,
      },
    },
    cruiser: {
      factionName: "The Union",
      shipId: "CR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Cruiser",
      x: 100,
      y: 100,
      width: 123,
      height: 245,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Faction6%2FChatGPT%20Image%20May%2026%2C%202025%2C%2009_57_21%20AM.png?alt=media&token=bf3f7c8e-9f0d-43c9-a9c0-54ff4a02783b",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 12,
      hp: 12,
      damageThreshold: 6,
      threatLevel: 8,
      moveDistance: 50,
      weaponType: ["Heavy Cannon", "Plasma Cannon"],
      firingArc: "Forward(90°) \nPortside(90°)/Starboard(90°)",
      weaponDamage: "1d8 \n1d10",
      weaponRange: "30ft \n60ft",
      pointValue: 80,
      specialOrders: {
        "Full Throttle": false,
        "All Systems Fire": false,
        "Reinforce Shields": false,
        Broadside: false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Heavy Cannon": false,
        "Plasma Cannon": false,
      },
    },
    carrier: {
      factionName: "The Union",
      shipId: "CA-ID:" + " " + new Date().getMilliseconds(5),
      type: "Carrier",
      x: 100,
      y: 100,
      width: 104,
      height: 208,
      isSelected: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Faction6%2FChatGPT%20Image%20May%2026%2C%202025%2C%2010_26_19%20AM.png?alt=media&token=4a879f41-902a-4f56-a8d3-f21691cec427",
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      maxHP: 14,
      hp: 14,
      damageThreshold: 7,
      threatLevel: 9,
      moveDistance: 40,
      weaponType: ["=Missile Battery"],
      weaponStatus: { "Missile Battery": false },
      firingArc: "Forward(90°) \nAll(360°)",
      weaponDamage: "1d8 \n1d6",
      weaponRange: "30ft-120ft \n15ft-60ft",
      pointValue: 120,
      specialOrders: {
        "Full Throttle": false,
        "Reinforce Shields": false,
        "Launch Fighters": false,
        "All Systems Fire": false,
      },
      hasBeenInteractedWith: false,
      maxCapacity: 20,
      capacity: 20,
    },
    dreadnought: {
      factionName: "The Union",
      shipId: "DR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Dreadnought",
      x: 100,
      y: 100,
      width: 218,
      height: 371,
      isSelected: false,

      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Faction6%2FChatGPT%20Image%20May%2026%2C%202025%2C%2009_47_36%20AM.png?alt=media&token=9971a23d-fa35-47da-98f8-d4e77ebd660e",
      maxHP: 30,
      hp: 30,
      damageThreshold: 4,
      threatLevel: 8,
      moveDistance: 30,
      weaponType: ["Ion Particle Beam", "Plasma Cannon", "350mm Railgun"],
      firingArc:
        "Forward(90°) \nPortside(90°)/Starboard(90°) \nForward(90°)/Aft(90°)",
      weaponDamage: "1d12\n1d10\n1d8",
      weaponRange: "30ft-60ft \n60ft \n30ft-120ft",
      pointValue: 240,
      bonuses: {
        moveDistanceBonus: 0,
        broadSideBonus: 0,
        inFighterRangeBonus: 0,
      },
      specialOrders: {
        "Full Throttle": false,
        "Reinforce Shields": false,
        "All Systems Fire": false,
        "Charge Ion Beam": false,
      },
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Ion Particle Beam": false,
        "Plasma Cannon": false,
        "350mm Railgun": false,
      },
    },
  },
};
