export const shipObject = {
  "Nova Raiders": {
    fighter: {
      id: Date.now().toString(),
      user: "",
      username: "",
      factionName: "Nova Raiders",
      shipId: "FG-ID:" + " " + new Date().getMilliseconds(5),
      type: "Fighter",
      x: 100,
      y: 100,
      prevX: 0,
      prevY: 0,
      width: 68,
      height: 86,
      isSelected: false,
      highlighted: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/loa_fox.png?alt=media&token=e045de71-1b0a-444c-b93b-8092c0c2b738",
      globalAlpha: 1,
      maxHP: 20,
      hp: 20,
      damageThreshold: 1,
      threatLevel: 15,
      moveDistance: 80,
      weaponType: "Light Cannon",
      firingArc: "Forward(90°)",
      weaponDamage: "1d4",
      weaponRange: 30,
      pointValue: 1,
      orders: "Full Throttle \n Combine Fire \nEvasive Maneuvers",
      ordersUsed: 0,
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Light Cannon": false,
      },
    },

    destroyer: {
      id: Date.now().toString(),
      user: "",
      username: "",
      factionName: "Nova Raiders",
      shipId: "DE-ID:" + " " + new Date().getMilliseconds(5),
      type: "Destroyer",
      x: 100,
      y: 100,
      prevX: 0,
      prevY: 0,
      width: 104,
      height: 208,
      isSelected: false,
      highlighted: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/al_victoria.png?alt=media&token=41f7715f-a743-481e-b37a-85d680689d1d",
      globalAlpha: 1,
      maxHP: 8,
      hp: 8,
      damageThreshold: 4,
      threatLevel: 10,
      moveDistance: 60,
      weaponType: "Medium Cannon",
      firingArc: "Forward(90°)",
      weaponDamage: "1d10",
      weaponRange: 30,
      pointValue: 30,
      orders: "Full Throttle \nAnti-Fighter Barrage \nPower Up Main Guns",
      ordersUsed: 0,
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Medium Cannon": false,
      },
    },
    cruiser: {
      id: Date.now().toString(),
      user: "",
      username: "",
      factionName: "Nova Raiders",
      shipId: "CR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Cruiser",
      x: 100,
      y: 100,
      prevX: 0,
      prevY: 0,
      width: 123,
      height: 245,
      isSelected: false,
      highlighted: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/loa_hawke.png?alt=media&token=e2282fe0-e707-4694-9bfd-7a7b0927f3b0",
      globalAlpha: 1,
      maxHP: 12,
      hp: 12,
      damageThreshold: 6,
      threatLevel: 8,
      moveDistance: 50,
      weaponType: "Heavy Cannon \nPlasma Cannon",
      firingArc: "Forward(90°) \nPortside(90°)/Starboard(90°)",
      weaponDamage: "1d8 \n1d10",
      weaponRange: "30ft \n60ft",
      pointValue: 80,
      orders:
        "Full Throttle \nAll Systems Fire \nReinforce Shields \nBroadside",
      ordersUsed: 0,
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Heavy Cannon": false,
        "Plasma Cannon": false,
      },
    },
    carrier: {
      id: Date.now().toString(),
      user: "",
      username: "",
      factionName: "Nova Raiders",
      shipId: "CA-ID:" + " " + new Date().getMilliseconds(5),
      type: "Carrier",
      x: 100,
      y: 100,
      prevX: 0,
      prevY: 0,
      width: 104,
      height: 208,
      isSelected: false,
      highlighted: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/al_macnamara.png?alt=media&token=91c354ce-859f-4975-8283-430fa1759c13d",
      globalAlpha: 1,
      maxHP: 14,
      hp: 14,
      damageThreshold: 7,
      threatLevel: 9,
      moveDistance: 40,
      weaponType: "350mm Railguns \nMissile Battery",
      firingArc: "Forward(90°) \nAll(360°)",
      weaponDamage: "1d8 \n1d6",
      weaponRange: "30ft-120ft \n15ft-60ft",
      pointValue: 120,
      orders:
        "Full Throttle \nReinforce Shields Launch Fighters \nAll Systems Fire",
      ordersUsed: 0,
      hasBeenInteractedWith: false,
      weaponStatus: {
        "350mm Railgun": false,
        "Missile Battery": false,
      },
    },
    dreadnought: {
      id: Date.now().toString(),
      user: "",
      username: "",
      factionName: "Nova Raiders",
      shipId: "DR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Dreadnought",
      x: 100,
      y: 100,
      prevX: 0,
      prevY: 0,
      width: 218,
      height: 371,
      isSelected: false,
      highlighted: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/loa_alastair.png?alt=media&token=c99e1f58-7322-49bb-b3ae-9080ad55ee27",
      globalAlpha: 1,
      maxHP: 30,
      hp: 30,
      damageThreshold: 4,
      threatLevel: 8,
      moveDistance: 30,
      weaponType: "Ion Partical Beam \nPlasma Cannon \n350mm Railgun",
      firingArc:
        "Forward(90°) \nPortside(90°)/Starboard(90°) \nForward(90°)/Aft(90°)",
      weaponDamage: "1d12\n1d10\n1d8",
      weaponRange: "30ft-60ft \n60ft \n30ft-120ft",
      pointValue: 240,
      orders:
        "Full Throttle \nReinforce Shields \nLaunch Fighters \nAll Systems Fire \nCharge Ion Beam",
      ordersUsed: 0,
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Ion Particle Beam": false,
        "Plasma Cannon": false,
        "350mm Railgun": false,
      },
    },
  },
  "The Zyrrians": {
    fighter: {
      id: Date.now().toString(),
      user: "",
      username: "",
      factionName: "The Zyrrians",
      shipId: "FG-ID:" + " " + new Date().getMilliseconds(5),
      type: "Fighter",
      x: 100,
      y: 100,
      prevX: 0,
      prevY: 0,
      width: 68,
      height: 86,
      isSelected: false,
      highlighted: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/ms_morningstar_red.png?alt=media&token=8affea49-cebe-4074-9e20-ce3bb005b411",
      globalAlpha: 1,
      maxHP: 20,
      hp: 20,
      damageThreshold: 1,
      threatLevel: 15,
      moveDistance: 80,
      weaponType: "Light Cannon",
      firingArc: "Forward(90°)",
      weaponDamage: "1d4",
      weaponRange: 30,
      pointValue: 1,
      orders: "Full Throttle \n Combine Fire \nEvasive Maneuvers",
      ordersUsed: 0,
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Light Cannon": false,
      },
    },

    destroyer: {
      id: Date.now().toString(),
      user: "",
      username: "",
      factionName: "The Zyrrians",
      shipId: "DE-ID:" + " " + new Date().getMilliseconds(5),
      type: "Destroyer",
      x: 100,
      y: 100,
      prevX: 0,
      prevY: 0,
      width: 104,
      height: 208,
      isSelected: false,
      highlighted: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/ms_elysium_red.png?alt=media&token=d24ba855-fb1c-4655-b2e8-f445112014fa",
      globalAlpha: 1,
      maxHP: 8,
      hp: 8,
      damageThreshold: 4,
      threatLevel: 10,
      moveDistance: 60,
      weaponType: "Medium Cannon",
      firingArc: "Forward(90°)",
      weaponDamage: "1d10",
      weaponRange: 30,
      pointValue: 30,
      orders: "Full Throttle \nAnti-Fighter Barrage \nPower Up Main Guns",
      ordersUsed: 0,
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Medium Cannon": false,
      },
    },
    cruiser: {
      id: Date.now().toString(),
      user: "",
      username: "",
      factionName: "The Zyrrians",
      shipId: "CR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Cruiser",
      x: 100,
      y: 100,
      prevX: 0,
      prevY: 0,
      width: 123,
      height: 245,
      isSelected: false,
      highlighted: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/ms_charybdis_red.png?alt=media&token=c8c94379-8b70-41dd-ab37-6c3509467233",
      globalAlpha: 1,
      maxHP: 12,
      hp: 12,
      damageThreshold: 6,
      threatLevel: 8,
      moveDistance: 50,
      weaponType: "Heavy Cannon \nPlasma Cannon",
      firingArc: "Forward(90°) \nPortside(90°)/Starboard(90°)",
      weaponDamage: "1d8 \n1d10",
      weaponRange: "30ft \n60ft",
      pointValue: 80,
      orders:
        "Full Throttle \nAll Systems Fire \nReinforce Shields \nBroadside",
      ordersUsed: 0,
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Heavy Cannon": false,
        "Plasma Cannon": false,
      },
    },
    carrier: {
      id: Date.now().toString(),
      user: "",
      username: "",
      factionName: "The Zyrrians",
      shipId: "CA-ID:" + " " + new Date().getMilliseconds(5),
      type: "Carrier",
      x: 100,
      y: 100,
      prevX: 0,
      prevY: 0,
      width: 104,
      height: 208,
      isSelected: false,
      highlighted: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/ms_vardr_red.png?alt=media&token=b32f4425-e3fb-457d-9c86-e6eab694ad4f",
      globalAlpha: 1,
      maxHP: 14,
      hp: 14,
      damageThreshold: 7,
      threatLevel: 9,
      moveDistance: 40,
      weaponType: "350mm Railguns \nMissile Battery",
      firingArc: "Forward(90°) \nAll(360°)",
      weaponDamage: "1d8 \n1d6",
      weaponRange: "30ft-120ft \n15ft-60ft",
      pointValue: 120,
      orders:
        "Full Throttle \nReinforce Shields Launch Fighters \nAll Systems Fire",
      ordersUsed: 0,
      hasBeenInteractedWith: false,
      weaponStatus: {
        "350mm Railgun": false,
        "Missile Battery": false,
      },
    },
    dreadnought: {
      id: Date.now().toString(),
      user: "",
      username: "",
      factionName: "The Zyrrians",
      shipId: "DR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Dreadnought",
      x: 100,
      y: 100,
      prevX: 0,
      prevY: 0,
      width: 218,
      height: 371,
      isSelected: false,
      highlighted: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/ms_skadi_red.png?alt=media&token=e823f921-aa21-485c-9cdd-a19237e96e46",
      globalAlpha: 1,
      maxHP: 30,
      hp: 30,
      damageThreshold: 4,
      threatLevel: 8,
      moveDistance: 30,
      weaponType: "Ion Partical Beam \nPlasma Cannon \n350mm Railgun",
      firingArc:
        "Forward(90°) \nPortside(90°)/Starboard(90°) \nForward(90°)/Aft(90°)",
      weaponDamage: "1d12\n1d10\n1d8",
      weaponRange: "30ft-60ft \n60ft \n30ft-120ft",
      pointValue: 240,
      orders:
        "Full Throttle \nReinforce Shields \nLaunch Fighters \nAll Systems Fire \nCharge Ion Beam",
      ordersUsed: 0,
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Ion Particle Beam": false,
        "Plasma Cannon": false,
        "350mm Railgun": false,
      },
    },
  },
  "Voidborn Marauders": {
    fighter: {
      id: Date.now().toString(),
      user: "",
      username: "",
      factionName: "Voidborn Marauders",
      shipId: "FG-ID:" + " " + new Date().getMilliseconds(5),
      type: "Fighter",
      x: 100,
      y: 100,
      prevX: 0,
      prevY: 0,
      width: 68,
      height: 86,
      isSelected: false,
      highlighted: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/diableavionics_laminar.png?alt=media&token=dea06d87-9bdb-4492-8e83-f60749521255",
      globalAlpha: 1,
      maxHP: 20,
      hp: 20,
      damageThreshold: 1,
      threatLevel: 15,
      moveDistance: 80,
      weaponType: "Light Cannon",
      firingArc: "Forward(90°)",
      weaponDamage: "1d4",
      weaponRange: 30,
      pointValue: 1,
      orders: "Full Throttle \n Combine Fire \nEvasive Maneuvers",
      ordersUsed: 0,
      weaponStatus: {
        "Light Cannon": false,
      },
    },

    destroyer: {
      id: Date.now().toString(),
      user: "",
      username: "",
      factionName: "Voidborn Marauders",
      shipId: "DE-ID:" + " " + new Date().getMilliseconds(5),
      type: "Destroyer",
      x: 100,
      y: 100,
      prevX: 0,
      prevY: 0,
      width: 104,
      height: 208,
      isSelected: false,
      highlighted: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/diableavionics_calm_deck.png?alt=media&token=d101d81f-e59c-4ab0-a3f0-cc7311e65dc0",
      globalAlpha: 1,
      maxHP: 8,
      hp: 8,
      damageThreshold: 4,
      threatLevel: 10,
      moveDistance: 60,
      weaponType: "Medium Cannon",
      firingArc: "Forward(90°)",
      weaponDamage: "1d10",
      weaponRange: 30,
      pointValue: 30,
      orders: "Full Throttle \nAnti-Fighter Barrage \nPower Up Main Guns",
      ordersUsed: 0,
      weaponStatus: {
        "Medium Cannon": false,
      },
    },
    cruiser: {
      id: Date.now().toString(),
      user: "",
      username: "",
      factionName: "Voidborn Marauders",
      shipId: "CR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Cruiser",
      x: 100,
      y: 100,
      prevX: 0,
      prevY: 0,
      width: 123,
      height: 245,
      isSelected: false,
      highlighted: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/diableavionics_storm.png?alt=media&token=855c13c0-ad72-404c-8468-e007d44faaa1",
      globalAlpha: 1,
      maxHP: 12,
      hp: 12,
      damageThreshold: 6,
      threatLevel: 8,
      moveDistance: 50,
      weaponType: "Heavy Cannon \nPlasma Cannon",
      firingArc: "Forward(90°) \nPortside(90°)/Starboard(90°)",
      weaponDamage: "1d8 \n1d10",
      weaponRange: "30ft \n60ft",
      pointValue: 80,
      orders:
        "Full Throttle \nAll Systems Fire \nReinforce Shields \nBroadside",
      ordersUsed: 0,
      weaponStatus: {
        "Heavy Cannon": false,
        "Plasma Cannon": false,
      },
    },
    carrier: {
      id: Date.now().toString(),
      user: "",
      username: "",
      factionName: "Voidborn Marauders",
      shipId: "CA-ID:" + " " + new Date().getMilliseconds(5),
      type: "Carrier",
      x: 100,
      y: 100,
      prevX: 0,
      prevY: 0,
      width: 104,
      height: 208,
      isSelected: false,
      highlighted: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/diableavionics_maelstrom.png?alt=media&token=3ce1a2e0-e2e0-47c4-99ac-65bed80062a9",
      globalAlpha: 1,
      maxHP: 14,
      hp: 14,
      damageThreshold: 7,
      threatLevel: 9,
      moveDistance: 40,
      weaponType: "350mm Railguns \nMissile Battery",
      firingArc: "Forward(90°) \nAll(360°)",
      weaponDamage: "1d8 \n1d6",
      weaponRange: "30ft-120ft \n15ft-60ft",
      pointValue: 120,
      orders:
        "Full Throttle \nReinforce Shields Launch Fighters \nAll Systems Fire",
      ordersUsed: 0,
      weaponStatus: {
        "350mm Railgun": false,
        "Missile Battery": false,
      },
    },
    dreadnought: {
      id: Date.now().toString(),
      user: "",
      username: "",
      factionName: "Voidborn Marauders",
      shipId: "DR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Dreadnought",
      x: 100,
      y: 100,
      prevX: 0,
      prevY: 0,
      width: 218,
      height: 371,
      isSelected: false,
      highlighted: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/diableavionics_pandemonium.png?alt=media&token=25124de9-69d8-4af2-bc91-21160af1f2c1",
      globalAlpha: 1,
      maxHP: 30,
      hp: 30,
      damageThreshold: 4,
      threatLevel: 8,
      moveDistance: 30,
      weaponType: "Ion Partical Beam \nPlasma Cannon \n350mm Railgun",
      firingArc:
        "Forward(90°) \nPortside(90°)/Starboard(90°) \nForward(90°)/Aft(90°)",
      weaponDamage: "1d12\n1d10\n1d8",
      weaponRange: "30ft-60ft \n60ft \n30ft-120ft",
      pointValue: 240,
      orders:
        "Full Throttle \nReinforce Shields \nLaunch Fighters \nAll Systems Fire \nCharge Ion Beam",
      ordersUsed: 0,
      weaponStatus: {
        "Ion Particle Beam": false,
        "Plasma Cannon": false,
        "350mm Railgun": false,
      },
    },
  },
  "Star Reapers": {
    fighter: {
      id: Date.now().toString(),
      user: "",
      username: "",
      factionName: "Star Reapers",
      shipId: "FG-ID:" + " " + new Date().getMilliseconds(5),
      type: "Fighter",
      x: 100,
      y: 100,
      prevX: 0,
      prevY: 0,
      width: 68,
      height: 86,
      isSelected: false,
      highlighted: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/PLSP_meteoroid.png?alt=media&token=8b24e55a-d26c-43af-a7bd-0256a638e6ac",
      globalAlpha: 1,
      maxHP: 20,
      hp: 20,
      damageThreshold: 1,
      threatLevel: 15,
      moveDistance: 80,
      weaponType: "Light Cannon",
      firingArc: "Forward(90°)",
      weaponDamage: "1d4",
      weaponRange: 30,
      pointValue: 1,
      orders: "Full Throttle \n Combine Fire \nEvasive Maneuvers",
      ordersUsed: 0,
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Light Cannon": false,
      },
    },

    destroyer: {
      id: Date.now().toString(),
      user: "",
      username: "",
      factionName: "Star Reapers",
      shipId: "DE-ID:" + " " + new Date().getMilliseconds(5),
      type: "Destroyer",
      x: 100,
      y: 100,
      prevX: 0,
      prevY: 0,
      width: 104,
      height: 208,
      isSelected: false,
      highlighted: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/PLSP_linghtcone.png?alt=media&token=48ad88e9-cfe1-45e7-a728-144e405c66a9",
      globalAlpha: 1,
      maxHP: 8,
      hp: 8,
      damageThreshold: 4,
      threatLevel: 10,
      moveDistance: 60,
      weaponType: "Medium Cannon",
      firingArc: "Forward(90°)",
      weaponDamage: "1d10",
      weaponRange: 30,
      pointValue: 30,
      orders: "Full Throttle \nAnti-Fighter Barrage \nPower Up Main Guns",
      ordersUsed: 0,
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Medium Cannon": false,
      },
    },
    cruiser: {
      id: Date.now().toString(),
      user: "",
      username: "",
      factionName: "Star Reapers",
      shipId: "CR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Cruiser",
      x: 100,
      y: 100,
      prevX: 0,
      prevY: 0,
      width: 123,
      height: 245,
      isSelected: false,
      highlighted: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/PLSP_axis.png?alt=media&token=0702bb1b-5573-4bba-b5b7-11a4f297fa0f",
      globalAlpha: 1,
      maxHP: 12,
      hp: 12,
      damageThreshold: 6,
      threatLevel: 8,
      moveDistance: 50,
      weaponType: "Heavy Cannon \nPlasma Cannon",
      firingArc: "Forward(90°) \nPortside(90°)/Starboard(90°)",
      weaponDamage: "1d8 \n1d10",
      weaponRange: "30ft \n60ft",
      pointValue: 80,
      orders:
        "Full Throttle \nAll Systems Fire \nReinforce Shields \nBroadside",
      ordersUsed: 0,
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Heavy Cannon": false,
        "Plasma Cannon": false,
      },
    },
    carrier: {
      id: Date.now().toString(),
      user: "",
      username: "",
      factionName: "Star Reapers",
      shipId: "CA-ID:" + " " + new Date().getMilliseconds(5),
      type: "Carrier",
      x: 100,
      y: 100,
      prevX: 0,
      prevY: 0,
      width: 104,
      height: 208,
      isSelected: false,
      highlighted: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/PLSP_horizon.png?alt=media&token=c37f7b56-f07d-44ec-8b67-2d92bb3d70f4",
      globalAlpha: 1,
      maxHP: 14,
      hp: 14,
      damageThreshold: 7,
      threatLevel: 9,
      moveDistance: 40,
      weaponType: "350mm Railguns \nMissile Battery",
      firingArc: "Forward(90°) \nAll(360°)",
      weaponDamage: "1d8 \n1d6",
      weaponRange: "30ft-120ft \n15ft-60ft",
      pointValue: 120,
      orders:
        "Full Throttle \nReinforce Shields Launch Fighters \nAll Systems Fire",
      ordersUsed: 0,
      hasBeenInteractedWith: false,
      weaponStatus: {
        "350mm Railgun": false,
        "Missile Battery": false,
      },
    },
    dreadnought: {
      id: Date.now().toString(),
      user: "",
      username: "",
      factionName: "Star Reapers",
      shipId: "DR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Dreadnought",
      x: 100,
      y: 100,
      prevX: 0,
      prevY: 0,
      width: 218,
      height: 371,
      isSelected: false,
      highlighted: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/PLSP_flocculus.png?alt=media&token=594e0269-0944-4e46-bf69-acbb345edb79",
      globalAlpha: 1,
      maxHP: 30,
      hp: 30,
      damageThreshold: 4,
      threatLevel: 8,
      moveDistance: 30,
      weaponType: "Ion Partical Beam \nPlasma Cannon \n350mm Railgun",
      firingArc:
        "Forward(90°) \nPortside(90°)/Starboard(90°) \nForward(90°)/Aft(90°)",
      weaponDamage: "1d12\n1d10\n1d8",
      weaponRange: "30ft-60ft \n60ft \n30ft-120ft",
      pointValue: 240,
      orders:
        "Full Throttle \nReinforce Shields \nLaunch Fighters \nAll Systems Fire \nCharge Ion Beam",
      ordersUsed: 0,
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Ion Particle Beam": false,
        "Plasma Cannon": false,
        "350mm Railgun": false,
      },
    },
  },
  "Praxleon Empire": {
    fighter: {
      id: Date.now().toString(),
      user: "",
      username: "",
      factionName: "Praxleon Empire",
      shipId: "FG-ID:" + " " + new Date().getMilliseconds(5),
      type: "Fighter",
      x: 100,
      y: 100,
      prevX: 0,
      prevY: 0,
      width: 68,
      height: 86,
      isSelected: false,
      highlighted: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/expsp_korsettes.png?alt=media&token=62e621b3-7b7d-4b4d-84b2-0b5896dd8ff1",
      globalAlpha: 1,
      maxHP: 20,
      hp: 20,
      damageThreshold: 1,
      threatLevel: 15,
      moveDistance: 80,
      weaponType: "Light Cannon",
      firingArc: "Forward(90°)",
      weaponDamage: "1d4",
      weaponRange: 30,
      pointValue: 1,
      orders: "Full Throttle \n Combine Fire \nEvasive Maneuvers",
      ordersUsed: 0,
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Light Cannon": false,
      },
    },

    destroyer: {
      id: Date.now().toString(),
      user: "",
      username: "",
      factionName: "Praxleon Empire",
      shipId: "DE-ID:" + " " + new Date().getMilliseconds(5),
      type: "Destroyer",
      x: 100,
      y: 100,
      prevX: 0,
      prevY: 0,
      width: 104,
      height: 208,
      isSelected: false,
      highlighted: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/expsp_scholarmvs.png?alt=media&token=c492487d-579c-48f2-afae-477ec718208a",
      globalAlpha: 1,
      maxHP: 8,
      hp: 8,
      damageThreshold: 4,
      threatLevel: 10,
      moveDistance: 60,
      weaponType: "Medium Cannon",
      firingArc: "Forward(90°)",
      weaponDamage: "1d10",
      weaponRange: 30,
      pointValue: 30,
      orders: "Full Throttle \nAnti-Fighter Barrage \nPower Up Main Guns",
      ordersUsed: 0,
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Medium Cannon": false,
      },
    },
    cruiser: {
      id: Date.now().toString(),
      user: "",
      username: "",
      factionName: "Praxleon Empire",
      shipId: "CR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Cruiser",
      x: 100,
      y: 100,
      prevX: 0,
      prevY: 0,
      width: 123,
      height: 245,
      isSelected: false,
      highlighted: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/expsp_helena_mil.png?alt=media&token=a488e7c8-f6c5-40f4-8427-66e6514fc6c7",
      globalAlpha: 1,
      maxHP: 12,
      hp: 12,
      damageThreshold: 6,
      threatLevel: 8,
      moveDistance: 50,
      weaponType: "Heavy Cannon \nPlasma Cannon",
      firingArc: "Forward(90°) \nPortside(90°)/Starboard(90°)",
      weaponDamage: "1d8 \n1d10",
      weaponRange: "30ft \n60ft",
      pointValue: 80,
      orders:
        "Full Throttle \nAll Systems Fire \nReinforce Shields \nBroadside",
      ordersUsed: 0,
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Heavy Cannon": false,
        "Plasma Cannon": false,
      },
    },
    carrier: {
      id: Date.now().toString(),
      user: "",
      username: "",
      factionName: "Praxleon Empire",
      shipId: "CA-ID:" + " " + new Date().getMilliseconds(5),
      type: "Carrier",
      x: 100,
      y: 100,
      prevX: 0,
      prevY: 0,
      width: 104,
      height: 208,
      isSelected: false,
      highlighted: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/expsp_abysswalker.png?alt=media&token=a051ac62-f2a5-4962-8933-e87b033fc914",
      globalAlpha: 1,
      maxHP: 14,
      hp: 14,
      damageThreshold: 7,
      threatLevel: 9,
      moveDistance: 40,
      weaponType: "350mm Railguns \nMissile Battery",
      firingArc: "Forward(90°) \nAll(360°)",
      weaponDamage: "1d8 \n1d6",
      weaponRange: "30ft-120ft \n15ft-60ft",
      pointValue: 120,
      orders:
        "Full Throttle \nReinforce Shields Launch Fighters \nAll Systems Fire",
      ordersUsed: 0,
      hasBeenInteractedWith: false,
      weaponStatus: {
        "350mm Railgun": false,
        "Missile Battery": false,
      },
    },
    dreadnought: {
      id: Date.now().toString(),
      user: "",
      username: "",
      factionName: "Praxleon Empire",
      shipId: "DR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Dreadnought",
      x: 100,
      y: 100,
      prevX: 0,
      prevY: 0,
      width: 218,
      height: 371,
      isSelected: false,
      highlighted: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/expsp_dragonhunter.png?alt=media&token=212773dc-fad9-45b2-8ca0-25805574359d",
      globalAlpha: 1,
      maxHP: 30,
      hp: 30,
      damageThreshold: 4,
      threatLevel: 8,
      moveDistance: 30,
      weaponType: "Ion Partical Beam \nPlasma Cannon \n350mm Railgun",
      firingArc:
        "Forward(90°) \nPortside(90°)/Starboard(90°) \nForward(90°)/Aft(90°)",
      weaponDamage: "1d12\n1d10\n1d8",
      weaponRange: "30ft-60ft \n60ft \n30ft-120ft",
      pointValue: 240,
      orders:
        "Full Throttle \nReinforce Shields \nLaunch Fighters \nAll Systems Fire \nCharge Ion Beam",
      ordersUsed: 0,
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Ion Particle Beam": false,
        "Plasma Cannon": false,
        "350mm Railgun": false,
      },
    },
  },
  "Synthon Syndicate": {
    fighter: {
      id: Date.now().toString(),
      user: "",
      username: "",
      factionName: "Synthon Syndicate",
      shipId: "FG-ID:" + " " + new Date().getMilliseconds(5),
      type: "Fighter",
      x: 100,
      y: 100,
      prevX: 0,
      prevY: 0,
      width: 68,
      height: 86,
      isSelected: false,
      highlighted: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Nightseer.png?alt=media&token=af136f07-a921-40c9-819c-9f43ff6ed95d",
      globalAlpha: 1,
      maxHP: 20,
      hp: 20,
      damageThreshold: 1,
      threatLevel: 15,
      moveDistance: 80,
      weaponType: "Light Cannon",
      firingArc: "Forward(90°)",
      weaponDamage: "1d4",
      weaponRange: 30,
      pointValue: 1,
      orders: "Full Throttle \n Combine Fire \nEvasive Maneuvers",
      ordersUsed: 0,
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Light Cannon": false,
      },
    },

    destroyer: {
      id: Date.now().toString(),
      user: "",
      username: "",
      factionName: "Synthon Syndicate",
      shipId: "DE-ID:" + " " + new Date().getMilliseconds(5),
      type: "Destroyer",
      x: 100,
      y: 100,
      prevX: 0,
      prevY: 0,
      width: 104,
      height: 208,
      isSelected: false,
      highlighted: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Soulbane.png?alt=media&token=0c2194d9-181b-478f-9573-09b02374e586",
      globalAlpha: 1,
      maxHP: 8,
      hp: 8,
      damageThreshold: 4,
      threatLevel: 10,
      moveDistance: 60,
      weaponType: "Medium Cannon",
      firingArc: "Forward(90°)",
      weaponDamage: "1d10",
      weaponRange: 30,
      pointValue: 30,
      orders: "Full Throttle \nAnti-Fighter Barrage \nPower Up Main Guns",
      ordersUsed: 0,
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Medium Cannon": false,
      },
    },
    cruiser: {
      id: Date.now().toString(),
      user: "",
      username: "",
      factionName: "Synthon Syndicate",
      shipId: "CR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Cruiser",
      x: 100,
      y: 100,
      prevX: 0,
      prevY: 0,
      width: 123,
      height: 245,
      isSelected: false,
      highlighted: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/IHS_Orig.png?alt=media&token=28e12573-ff70-4a46-8d0c-3c45f400baf7",
      globalAlpha: 1,
      maxHP: 12,
      hp: 12,
      damageThreshold: 6,
      threatLevel: 8,
      moveDistance: 50,
      weaponType: "Heavy Cannon \nPlasma Cannon",
      firingArc: "Forward(90°) \nPortside(90°)/Starboard(90°)",
      weaponDamage: "1d8 \n1d10",
      weaponRange: "30ft \n60ft",
      pointValue: 80,
      orders:
        "Full Throttle \nAll Systems Fire \nReinforce Shields \nBroadside",
      ordersUsed: 0,
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Heavy Cannon": false,
        "Plasma Cannon": false,
      },
    },
    carrier: {
      id: Date.now().toString(),
      user: "",
      username: "",
      factionName: "Synthon Syndicate",
      shipId: "CA-ID:" + " " + new Date().getMilliseconds(5),
      type: "Carrier",
      x: 100,
      y: 100,
      prevX: 0,
      prevY: 0,
      width: 104,
      height: 208,
      isSelected: false,
      highlighted: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Kelpie.png?alt=media&token=f6d8d3f7-3e31-49c1-8d9b-32dd0c8e4870",
      globalAlpha: 1,
      maxHP: 14,
      hp: 14,
      damageThreshold: 7,
      threatLevel: 9,
      moveDistance: 40,
      weaponType: "350mm Railguns \nMissile Battery",
      firingArc: "Forward(90°) \nAll(360°)",
      weaponDamage: "1d8 \n1d6",
      weaponRange: "30ft-120ft \n15ft-60ft",
      pointValue: 120,
      orders:
        "Full Throttle \nReinforce Shields Launch Fighters \nAll Systems Fire",
      ordersUsed: 0,
      hasBeenInteractedWith: false,
      weaponStatus: {
        "350mm Railgun": false,
        "Missile Battery": false,
      },
    },
    dreadnought: {
      id: Date.now().toString(),
      user: "",
      username: "",
      factionName: "Synthon Syndicate",
      shipId: "DR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Dreadnought",
      x: 100,
      y: 100,
      prevX: 0,
      prevY: 0,
      width: 218,
      height: 371,
      isSelected: false,
      highlighted: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/Shalom.png?alt=media&token=40e901c7-a619-4da9-a343-015d30d0995f",
      globalAlpha: 1,
      maxHP: 30,
      hp: 30,
      damageThreshold: 4,
      threatLevel: 8,
      moveDistance: 30,
      weaponType: "Ion Partical Beam \nPlasma Cannon \n350mm Railgun",
      firingArc:
        "Forward(90°) \nPortside(90°)/Starboard(90°) \nForward(90°)/Aft(90°)",
      weaponDamage: "1d12\n1d10\n1d8",
      weaponRange: "30ft-60ft \n60ft \n30ft-120ft",
      pointValue: 240,
      orders:
        "Full Throttle \nReinforce Shields \nLaunch Fighters \nAll Systems Fire \nCharge Ion Beam",
      ordersUsed: 0,
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Ion Particle Beam": false,
        "Plasma Cannon": false,
        "350mm Railgun": false,
      },
    },
  },
  "The Union": {
    fighter: {
      id: Date.now().toString(),
      user: "",
      username: "",
      factionName: "The Union",
      shipId: "FG-ID:" + " " + new Date().getMilliseconds(5),
      type: "Fighter",
      x: 100,
      y: 100,
      prevX: 0,
      prevY: 0,
      width: 68,
      height: 86,
      isSelected: false,
      highlighted: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/neutrino_causality.png?alt=media&token=0fbf27e4-6c8d-425d-8389-85a3fbc1d803",
      globalAlpha: 1,
      maxHP: 20,
      hp: 20,
      damageThreshold: 1,
      threatLevel: 15,
      moveDistance: 80,
      weaponType: "Light Cannon",
      firingArc: "Forward(90°)",
      weaponDamage: "1d4",
      weaponRange: 30,
      pointValue: 1,
      orders: "Full Throttle \n Combine Fire \nEvasive Maneuvers",
      ordersUsed: 0,
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Light Cannon": false,
      },
    },

    destroyer: {
      id: Date.now().toString(),
      user: "",
      username: "",
      factionName: "The Union",
      shipId: "DE-ID:" + " " + new Date().getMilliseconds(5),
      type: "Destroyer",
      x: 100,
      y: 100,
      prevX: 0,
      prevY: 0,
      width: 104,
      height: 208,
      isSelected: false,
      highlighted: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/neutrino_lathe.png?alt=media&token=81451f40-1a48-4131-a813-440bfa55a700",
      globalAlpha: 1,
      maxHP: 8,
      hp: 8,
      damageThreshold: 4,
      threatLevel: 10,
      moveDistance: 60,
      weaponType: "Medium Cannon",
      firingArc: "Forward(90°)",
      weaponDamage: "1d10",
      weaponRange: 30,
      pointValue: 30,
      orders: "Full Throttle \nAnti-Fighter Barrage \nPower Up Main Guns",
      ordersUsed: 0,
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Medium Cannon": false,
      },
    },
    cruiser: {
      id: Date.now().toString(),
      user: "",
      username: "",
      factionName: "The Union",
      shipId: "CR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Cruiser",
      x: 100,
      y: 100,
      prevX: 0,
      prevY: 0,
      width: 123,
      height: 245,
      isSelected: false,
      highlighted: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/neutrino_nirvash.png?alt=media&token=c0c644c3-03e8-4bfe-9ec6-3a51cb2e70e0",
      globalAlpha: 1,
      maxHP: 12,
      hp: 12,
      damageThreshold: 6,
      threatLevel: 8,
      moveDistance: 50,
      weaponType: "Heavy Cannon \nPlasma Cannon",
      firingArc: "Forward(90°) \nPortside(90°)/Starboard(90°)",
      weaponDamage: "1d8 \n1d10",
      weaponRange: "30ft \n60ft",
      pointValue: 80,
      orders:
        "Full Throttle \nAll Systems Fire \nReinforce Shields \nBroadside",
      ordersUsed: 0,
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Heavy Cannon": false,
        "Plasma Cannon": false,
      },
    },
    carrier: {
      id: Date.now().toString(),
      user: "",
      username: "",
      factionName: "The Union",
      shipId: "CA-ID:" + " " + new Date().getMilliseconds(5),
      type: "Carrier",
      x: 100,
      y: 100,
      prevX: 0,
      prevY: 0,
      width: 104,
      height: 208,
      isSelected: false,
      highlighted: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/neutrino_nausicaa.png?alt=media&token=36f3ebaf-7702-4c48-8027-f55b607fb942",
      globalAlpha: 1,
      maxHP: 14,
      hp: 14,
      damageThreshold: 7,
      threatLevel: 9,
      moveDistance: 40,
      weaponType: "350mm Railguns \nMissile Battery",
      firingArc: "Forward(90°) \nAll(360°)",
      weaponDamage: "1d8 \n1d6",
      weaponRange: "30ft-120ft \n15ft-60ft",
      pointValue: 120,
      orders:
        "Full Throttle \nReinforce Shields Launch Fighters \nAll Systems Fire",
      ordersUsed: 0,
      hasBeenInteractedWith: false,
      weaponStatus: {
        "350mm Railgun": false,
        "Missile Battery": false,
      },
    },
    dreadnought: {
      id: Date.now().toString(),
      user: "",
      username: "",
      factionName: "The Union",
      shipId: "DR-ID:" + " " + new Date().getMilliseconds(5),
      type: "Dreadnought",
      x: 100,
      y: 100,
      prevX: 0,
      prevY: 0,
      width: 218,
      height: 371,
      isSelected: false,
      highlighted: false,
      isToggled: false,
      rotation_angle: 0,
      image:
        "https://firebasestorage.googleapis.com/v0/b/starbound-conquest-a1adc.firebasestorage.app/o/neutrino_unsung.png?alt=media&token=05140d5e-e08c-42de-b9a5-217606cfa4b8",
      globalAlpha: 1,
      maxHP: 30,
      hp: 30,
      damageThreshold: 4,
      threatLevel: 8,
      moveDistance: 30,
      weaponType: "Ion Partical Beam \nPlasma Cannon \n350mm Railgun",
      firingArc:
        "Forward(90°) \nPortside(90°)/Starboard(90°) \nForward(90°)/Aft(90°)",
      weaponDamage: "1d12\n1d10\n1d8",
      weaponRange: "30ft-60ft \n60ft \n30ft-120ft",
      pointValue: 240,
      orders:
        "Full Throttle \nReinforce Shields \nLaunch Fighters \nAll Systems Fire \nCharge Ion Beam",
      ordersUsed: 0,
      hasBeenInteractedWith: false,
      weaponStatus: {
        "Ion Particle Beam": false,
        "Plasma Cannon": false,
        "350mm Railgun": false,
      },
    },
  },
};
