import { SpecialOrders } from "./SpecialOrders.js";

export const ShipAttributes = {
  Destroyer: {
    hp: 8,
    toHit: 10,
    soak: 4,
    moveDistance: "60ft",
    specialOrders: [
      [SpecialOrders[1].name, SpecialOrders[1].text, SpecialOrders[1].icon],
      [SpecialOrders[4].name, SpecialOrders[4].text, SpecialOrders[4].icon],
      [SpecialOrders[5].name, SpecialOrders[5].text, SpecialOrders[5].icon],
    ],
    weaponType: ["Medium Cannon"],
    firingArc: "Forward(90°)",
    weaponDamage: "1d6",
    weaponRange: "30ft",
    pointValue: 30,
  },
  Cruiser: {
    hp: 12,
    toHit: 8,
    soak: 6,
    moveDistance: "50ft",
    specialOrders: [
      [SpecialOrders[1].name, SpecialOrders[1].text, SpecialOrders[1].icon],
      [SpecialOrders[7].name, SpecialOrders[7].text, SpecialOrders[7].icon],
      [SpecialOrders[6].name, SpecialOrders[6].text, SpecialOrders[6].icon],
      [SpecialOrders[8].name, SpecialOrders[8].text, SpecialOrders[8].icon],
    ],
    weaponType: ["Heavy Cannon", "Plasma Cannon"],
    firingArc: ["Forward(90°)", "Port/Starboard(90°)"],
    weaponDamage: ["1d8", "1d10"],
    weaponRange: ["30ft", "60ft"],
    pointValue: 80,
  },
  Carrier: {
    hp: 14,
    toHit: 6,
    soak: 7,
    moveDistance: "40ft",
    currentCapacity: 20,
    specialOrders: [
      [SpecialOrders[1].name, SpecialOrders[1].text, SpecialOrders[1].icon],
      [SpecialOrders[7].name, SpecialOrders[7].text, SpecialOrders[7].icon],
      [SpecialOrders[6].name, SpecialOrders[6].text, SpecialOrders[6].icon],
      [SpecialOrders[9].name, SpecialOrders[9].text, SpecialOrders[9].icon],
    ],
    weaponType: ["350mm Railgun", "Missile Battery"],
    firingArc: ["Forward/Aft(90°)", "All(360)"],
    weaponDamage: ["1d8", "1d6"],
    weaponRange: ["30ft-120ft", "15ft-60ft"],
    pointValue: 120,
  },
  Dreadnought: {
    hp: 30,
    toHit: 4,
    soak: 8,
    moveDistance: "30ft",
    currentCapacity: 20,
    specialOrders: [
      [SpecialOrders[1].name, SpecialOrders[1].text, SpecialOrders[1].icon],
      [SpecialOrders[7].name, SpecialOrders[7].text, SpecialOrders[7].icon],
      [SpecialOrders[6].name, SpecialOrders[6].text, SpecialOrders[6].icon],
      [SpecialOrders[10].name, SpecialOrders[10].text, SpecialOrders[10].icon],
    ],
    weaponType: ["350mm Railgun", "Plasma Canon"],
    specialWeaponType: ["Ion Particle Beam"],
    firingArc: ["Forward/Aft(90°)", "Port/Starboard(90°)", "Forward(90°)"],
    weaponDamage: ["1d12", "1d10", "1d8"],
    weaponRange: ["30ft-120ft", "60ft", "30ft-60ft"],
    pointValue: 240,
  },
};
